### ISSUE TITLE
ValueError("invalid literal for int() with base 10: 'x,xxx'") - Flight price change with points error...

### ISSUE THREAD

**Issue by causefx** [jdholtz/auto-southwest-check-in#104]
### Description

It seems there is a conversion or math error as points have a comma - need to convert to integer...

### To Reproduce

Run app with a price change on flight that was booked with points...  

### Version

Auto-Southwest Check-In v4.1

### Additional context

```
Successfully scheduled the following flights to check in for Me:
Flight from Phoenix to Seattle/Tacoma at 2023-09-19 23:55:00 UTC
Flight from Seattle/Tacoma to Phoenix at 2023-09-23 00:05:00 UTC

2023-06-13 11:52:31 DEBUG Process-1:2[checkin_handler:58]: Sleeping until ten minutes before check-in...
2023-06-13 11:52:33 DEBUG Process-1[checkin_scheduler:51]: Removing departed flights. Currently have 2 flights scheduled
2023-06-13 11:52:33 DEBUG Process-1[checkin_scheduler:60]: Successfully removed departed flights. 2 flights are now scheduled
2023-06-13 11:52:33 DEBUG Process-1[flight_retriever:73]: Checking fares for 2 flights
2023-06-13 11:52:33 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2023-06-13 11:52:33 DEBUG Process-1[fare_checker:88]: Fetching reservation information
2023-06-13 11:52:35 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-13 11:52:35 DEBUG Process-1[fare_checker:103]: Retrieving search information for the current flight
2023-06-13 11:52:37 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-13 11:52:37 DEBUG Process-1[fare_checker:82]: Retrieving matching flights
2023-06-13 11:52:42 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-13 11:52:42 DEBUG Process-1[fare_checker:50]: Found 12 matching flights
2023-06-13 11:52:42 ERROR Process-1[flight_retriever:86]: Unexpected error during fare check: ValueError("invalid literal for int() with base 10: '1,855'")
Traceback (most recent call last):
  File "/app/lib/flight_retriever.py", line 80, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "/app/lib/fare_checker.py", line 35, in check_flight_price
    amount = int(flight_price["amount"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1,855'
2023-06-13 11:52:42 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2023-06-13 11:52:42 DEBUG Process-1[fare_checker:88]: Fetching reservation information
2023-06-13 11:52:44 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-13 11:52:44 DEBUG Process-1[fare_checker:103]: Retrieving search information for the current flight
2023-06-13 11:52:47 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-13 11:52:47 DEBUG Process-1[fare_checker:82]: Retrieving matching flights
2023-06-13 11:52:51 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-13 11:52:51 DEBUG Process-1[fare_checker:50]: Found 14 matching flights
2023-06-13 11:52:51 ERROR Process-1[flight_retriever:86]: Unexpected error during fare check: ValueError("invalid literal for int() with base 10: '3,447'")
Traceback (most recent call last):
  File "/app/lib/flight_retriever.py", line 80, in _check_flight_fares
    fare_checker.check_flight_price(flight)
  File "/app/lib/fare_checker.py", line 35, in check_flight_price
    amount = int(flight_price["amount"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '3,447'
2023-06-13 11:52:51 DEBUG Process-1[flight_retriever:96]: Sleeping for 86355 seconds
```

**Comment by jdholtz** [comment]
Thanks for reporting this issue. It seems to be from a change I just added. I pushed a fix for this in the latest commit on the `develop` branch. Could you make test it out to make sure you are not getting this issue anymore?

**Comment by causefx** [comment]
will do, I will report back :)

**Comment by causefx** [comment]
I'll have to test later...  

SW site having issues:
![image](https://github.com/jdholtz/auto-southwest-check-in/assets/16184466/9942f07b-e522-420b-904c-0c28dfac0c80)
```
2023-06-13 15:32:06 DEBUG Process-1[webdriver:90]: Logging into Southwest account to get scheduled flights and valid headers
2023-06-13 15:32:12 DEBUG Process-1[webdriver:225]: Logging in failed for an unknown reason
2023-06-13 15:32:12 DEBUG Process-1[flight_retriever:147]: Error logging in. Reason: Unknown. Status code: 500. Exiting
2023-06-13 15:32:12 DEBUG Process-1[notification_handler:75]: Sending failed login notification...
```

**Comment by causefx** [comment]
```
2023-06-14 07:01:03 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-14 07:01:03 DEBUG Process-1[fare_checker:50]: Found 12 matching flights
2023-06-14 07:01:03 DEBUG Process-1[fare_checker:37]: Flight price change found for 0 PTS
2023-06-14 07:01:03 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2023-06-14 07:01:03 DEBUG Process-1[fare_checker:88]: Fetching reservation information
2023-06-14 07:01:05 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-14 07:01:05 DEBUG Process-1[fare_checker:103]: Retrieving search information for the current flight
2023-06-14 07:01:07 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-14 07:01:07 DEBUG Process-1[fare_checker:82]: Retrieving matching flights
2023-06-14 07:01:10 DEBUG Process-1[utils:30]: Successfully made request after 1 attempts
2023-06-14 07:01:10 DEBUG Process-1[fare_checker:50]: Found 14 matching flights
2023-06-14 07:01:10 DEBUG Process-1[fare_checker:37]: Flight price change found for 0 PTS
2023-06-14 07:01:10 DEBUG Process-1[flight_retriever:96]: Sleeping for 86347 seconds
```
I would assume it works now as it shows zero points... :)

**Comment by jdholtz** [comment]
Thanks for testing! It actually should have said the change should be “1,855” or “3,447” but the points difference must have changed since you last checked.

**Comment by brianh-osu** [comment]
@jdholtz I'm getting this output today, is the issue related to this thread?

Monitoring 2 accounts and 0 reservations


Warning: uc_driver update needed. Getting it now:

*** chromedriver to download = 132.0.6834.110 (Latest Stable)

Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.110/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 4358, in get_local_driver
    sb_install.main(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\console_scripts\sb_install.py", line 908, in main
    zip_ref.extract(zipinfo, downloads_folder)
  File "C:\Program Files\Python38\lib\zipfile.py", line 1611, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Program Files\Python38\lib\zipfile.py", line 1682, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Brian\\OneDrive\\Documents\\southwest-auto-check-in\\auto-southwest-check-in\\.venv\\Lib\\site-packages\\seleniumbase\\drivers\\uc_driver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 51, in monitor
    self._monitor()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 69, in _monitor
    should_exit = self._check()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 187, in _check
    reservations, skip_scheduling = self._get_reservations()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 209, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\webdriver.py", line 101, in get_reservations
    driver = self._get_driver()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\webdriver.py", line 143, in _get_driver
    driver = Driver(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\plugins\driver_manager.py", line 793, in Driver
    driver = browser_launcher.get_driver(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 2699, in get_driver
    return get_local_driver(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 4368, in get_local_driver
    and int(use_version) > int(d_latest.split(".")[0])
ValueError: invalid literal for int() with base 10: '132.0.6834.110'

Warning: uc_driver update needed. Getting it now:

*** chromedriver to download = 132.0.6834.110 (Latest Stable)

Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.110/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 4358, in get_local_driver
    sb_install.main(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\console_scripts\sb_install.py", line 908, in main
    zip_ref.extract(zipinfo, downloads_folder)
  File "C:\Program Files\Python38\lib\zipfile.py", line 1611, in extract
    return self._extract_member(member, path, pwd)
  File "C:\Program Files\Python38\lib\zipfile.py", line 1682, in _extract_member
    open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Brian\\OneDrive\\Documents\\southwest-auto-check-in\\auto-southwest-check-in\\.venv\\Lib\\site-packages\\seleniumbase\\drivers\\uc_driver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 313, in _bootstrap
    self.run()
  File "C:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 51, in monitor
    self._monitor()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 69, in _monitor
    should_exit = self._check()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 187, in _check
    reservations, skip_scheduling = self._get_reservations()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\reservation_monitor.py", line 209, in _get_reservations
    reservations = webdriver.get_reservations(self)
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\webdriver.py", line 101, in get_reservations
    driver = self._get_driver()
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\lib\webdriver.py", line 143, in _get_driver
    driver = Driver(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\plugins\driver_manager.py", line 793, in Driver
    driver = browser_launcher.get_driver(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 2699, in get_driver
    return get_local_driver(
  File "C:\Users\Brian\OneDrive\Documents\southwest-auto-check-in\auto-southwest-check-in\.venv\lib\site-packages\seleniumbase\core\browser_launcher.py", line 4368, in get_local_driver
    and int(use_version) > int(d_latest.split(".")[0])
ValueError: invalid literal for int() with base 10: '132.0.6834.110'

**Comment by jdholtz** [comment]
> @jdholtz I'm getting this output today, is the issue related to this thread?

No, this appears to be a SeleniumBase issue. Try upgrading to the latest version via `pip install --upgrade seleniumbase`. If that doesn't work, I'd also file a separate issue/discussion in the [SeleniumBase](https://github.com/seleniumbase/SeleniumBase) repository if you can reproduce it with something similar to the code below (as this is what is done in the script):
```py
from seleniumbase import Driver
driver = Driver(
    driver_version="mlatest", headless=True, uc=True, uc_cdp_events=True, mobile=True, incognito=True
)
```
