### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate 

### ISSUE THREAD

**Issue by davewadestein** [jdholtz/auto-southwest-check-in#105]
### Description

Thanks for doing this!

Couldn't get it to work locally, here is the output with --verbose:

<details>
<summary>Output</summary>

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2023-06-13 15:12:36 DEBUG MainProcess[log]: Initialized the application
2023-06-13 15:12:36 DEBUG MainProcess[main]: Called with 3 arguments
2023-06-13 15:12:36 DEBUG MainProcess[config]: Reading the configuration file
2023-06-13 15:12:36 DEBUG MainProcess[config]: Adding 0 accounts from configuration file
2023-06-13 15:12:36 DEBUG MainProcess[config]: Setting check fares to False
2023-06-13 15:12:36 DEBUG MainProcess[config]: Adding 0 flights from configuration file
2023-06-13 15:12:36 DEBUG MainProcess[config]: Setting notification level to 1
2023-06-13 15:12:36 DEBUG MainProcess[config]: Using 1 notification services
2023-06-13 15:12:36 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-06-13 15:12:36 DEBUG MainProcess[main]: Flight added through CLI arguments
2023-06-13 15:12:36 DEBUG MainProcess[main]: Monitoring 0 accounts and 1 flights
2023-06-13 15:12:36 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-06-13 15:12:36 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-06-13 15:12:36 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-06-13 15:12:36 DEBUG Process-1[webdriver]: Starting webdriver for current session
2023-06-13 15:12:36 DEBUG Process-1[webdriver]: An exception occured when initializing the webdriver: Name: URLError. Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2023-06-13 15:12:36 DEBUG Process-1[webdriver]: 2 more attempts
2023-06-13 15:12:36 DEBUG Process-1[webdriver]: An exception occured when initializing the webdriver: Name: URLError. Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2023-06-13 15:12:36 DEBUG Process-1[webdriver]: 1 more attempts
2023-06-13 15:12:40 DEBUG Process-1[webdriver]: An exception occured when initializing the webdriver: Name: URLError. Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
2023-06-13 15:12:40 DEBUG Process-1[webdriver]: 0 more attempts
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

</details>

### To Reproduce

Maybe this is specific to my machine. Just running in a virtualenv.

Seems like it works in docker, so perhaps I will use it that way.

**Comment by davewadestein** [comment]
If no one else is getting this error, please close this. Must be my machine.

**Comment by davewadestein** [comment]
My certifi was not up to date, but once I updated it, I got the same error.

Thanks!
Dave

**Comment by jdholtz** [comment]
What operating system are you using? It would probably be best to look up the error on Google and use those suggestions to troubleshoot since the issue is specific to your machine.

**Comment by davewadestein** [comment]
I'm on a Mac (Ventura 13.4). But it seems to be working fine in Docker, so
I'll use that for now.

Sorry for the hassles!

Dave

**Comment by jdholtz** [comment]
No problem!
