### ISSUE TITLE
After successful check-in, "ValueError: list.remove(x): x not in list"

### ISSUE THREAD

**Issue by ericlamus** [jdholtz/auto-southwest-check-in#11]
Hello, I just noticed this in my console output.  This is with the fix-notifications branch.

```
Successfully logged in to Eric REDACTED's account

Scheduling checkin to flight from 'REDACTED' to 'REDACTED' for Eric REDACTED at 2022-09-04 REDACTED UTC

Checking in to flight from 'REDACTED' to 'REDACTED' for Eric REDACTED

Successfully checked in to flight from 'REDACTED' to 'REDACTED' for Eric REDACTED!
Eric REDACTED got B01!
Joe REDACTED got B02!

Process Process-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/eric/auto-southwest-check-in/lib/flight.py", line 80, in _set_check_in
    self.account.flights.remove(self)
ValueError: list.remove(x): x not in list
```

**Comment by jdholtz** [comment]
This seems to actually bring up a bigger issue from my fix for Issue #9 that I did not realize. However, this functionality isn't necessary at the moment, so I will just remove it.
