### ISSUE TITLE
The notifications and the check in did not work properly in 4.2 but works as expected in 4.1

### ISSUE THREAD

**Issue by dmytrokoren** [jdholtz/auto-southwest-check-in#119]
### Description

The notifications and the check in did not work properly in 4.2 but works as expected in 4.1

I have tried to check in with version 4.2 and it did not check me in on time and did not send me notification in terminal or in telegram(notifications setup properly - tested it). I went an ran the southwest.py once more after my check in window was open for about 1.5 hours and then it checked in..

After checked in I get this error:
```
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/reservation_monitor.py", line 116, in monitor
    self._schedule_reservations(reservations)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/reservation_monitor.py", line 64, in _schedule_reservations
    self.checkin_scheduler.process_reservations(confirmation_numbers)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/checkin_scheduler.py", line 45, in process_reservations
    self._schedule_flights(new_flights)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/checkin_scheduler.py", line 107, in _schedule_flights
    checkin_handler.schedule_check_in()
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/checkin_handler.py", line 39, in schedule_check_in
    self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object
```

### To Reproduce

Run southwest.py on 4.2

### Expected Behavior

In terminal for version 4.1 it shows:

```
Successfully logged in to John Doe's account

Successfully scheduled the following flights to check in for John Doe:
Flight from New York (LaGuardia) to Dallas (Love Field) at 2023-07-11 10:10:00 UTC
```

In terminal for version 4.2 it shows (incorrect):

```
Successfully logged in to John Doe's account
```
(Does not show that flight for check in will be schedule.) - and it did not, it just kept on showing Successfully logged in.

### Version

4.2

### Additional context

Thank you for looking into this and enhancing the script.

**Comment by jdholtz** [comment]
Hi. I changed the way check-ins are scheduled in 4.2. Was your computer ever in sleep mode from the time you started the script to the check-in time?

Can you attach your logs of the runs where it is not scheduling new flights for you?

**Comment by dmytrokoren** [comment]
Hi, probably my computer was a sleep at that time. I do not have the logs to attach as I delete the 4.2 and started using 4.1 version.

The issue/question that I have is that terminal is not notifying that the script is successfully scheduled to be checked.
Only showed for me that Successfully logged in to that account, when I did --verbose it said sleeping until 10 minutes till checkin.

Sorry I don't have the logs to attach but I like the way 4.1 is setup with Level notification in terminal.
Thanks in advance.

**Comment by jdholtz** [comment]
The script stores the last 5 runs in the `logs/` directory. If you have one of those that runs into the error you described, it would be great if you can attach it. It is very hard for me to debug this issue without the logs as I cannot reproduce it on my device.

This also might be an issue with running this script on macOS and Windows (I've only tested this version on Linux). I have both operating systems, so I can try on those and see if I run into the same issue.

**Comment by dmytrokoren** [comment]
I deleted the directory, I don't have any logs left from version 4.2 - as much as I would like to reproduce it myself, I cannot since the flight is already checked in.

can you please advise what's is the cause of this error?
`Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/reservation_monitor.py", line 116, in monitor
    self._schedule_reservations(reservations)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/reservation_monitor.py", line 64, in _schedule_reservations
    self.checkin_scheduler.process_reservations(confirmation_numbers)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/checkin_scheduler.py", line 45, in process_reservations
    self._schedule_flights(new_flights)
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/checkin_scheduler.py", line 107, in _schedule_flights
    checkin_handler.schedule_check_in()
  File "/Users/dima/Desktop/auto-southwest-check-in/lib/checkin_handler.py", line 39, in schedule_check_in
    self.process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref.ReferenceType' object`

**Comment by jdholtz** [comment]
I'm currently not sure why that issue is happening. I suspect that it has something to do with macOS and Windows. I will try to debug this issue further within the next few days.

If you want to, you can try the Docker image for v4.2 and see if that works for you.

**Comment by dmytrokoren** [comment]
I will try that, thank you JD.

**Comment by dmytrokoren** [comment]
Perfect. In Docker for Synology working perfectly. I will use that and it will never go to sleep -- Version 4.2 works great in Docker. Thanks JD

**Comment by jdholtz** [comment]
Great to hear! Thanks for trying it out. I will let you know when I have a fix for this

**Comment by jdholtz** [comment]
Hey @dmytrokoren. I made a potential fix for this in the [fix-process-handling](https://github.com/jdholtz/auto-southwest-check-in/tree/fix-process-handling) branch after being able to reproduce the issue. Would you be able to test out the changes on this new branch?

You can do so by issuing the following commands:
```
git pull
git checkout fix-process-handling
python southwest.py ...
```

**Comment by dmytrokoren** [comment]
@jdholtz I sure can once I reach back home. I will keep you posted. Thanks.

**Comment by jdholtz** [comment]
This issue is probably the same as #118. After you run the checkout command, you need to do another step to test this fix. Refer to the details [here](https://github.com/jdholtz/auto-southwest-check-in/issues/118#issuecomment-1632833108).

**Comment by dmytrokoren** [comment]
Hey @jdholtz, issue is fixed. Thanks for the quick fix. I'm closing this issue now, I think you can merge to master v.4.2.1 ;)

**Comment by jdholtz** [comment]
Thanks for testing!
