### ISSUE TITLE
Getting error with Fare Check

### ISSUE THREAD

**Issue by wootwoot1234** [jdholtz/auto-southwest-check-in#123]
### Description

Getting this error with fare check:

```

Unexpected error during fare check: AttributeError("'int' object has no attribute 'replace'")

Traceback (most recent call last):

  File "/app/lib/reservation_monitor.py", line 78, in _check_flight_fares

    fare_checker.check_flight_price(flight)

  File "/app/lib/fare_checker.py", line 35, in check_flight_price

    amount = int(flight_price["amount"].replace(",", ""))

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'int' object has no attribute 'replace'

Unexpected error during fare check: AttributeError("'int' object has no attribute 'replace'")

Traceback (most recent call last):

  File "/app/lib/reservation_monitor.py", line 78, in _check_flight_fares

    fare_checker.check_flight_price(flight)

  File "/app/lib/fare_checker.py", line 35, in check_flight_price

    amount = int(flight_price["amount"].replace(",", ""))

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'int' object has no attribute 'replace'
```

### To Reproduce

Run in docker

### Version

latest

**Comment by jdholtz** [comment]
See #122. I just fixed this in the develop branch (it has been an issue for a while). To apply the fix, you can use the `:develop` Docker image.
