### ISSUE TITLE
Incompatible with Chrome versions 116+

### ISSUE THREAD

**Issue by jdholtz** [jdholtz/auto-southwest-check-in#139]
### Version

All versions are affected

### Description

Due to restructuring of Chromedriver downloads by the Chromium team, versions >=115 of Chrome/Chromium are downloaded in a new place that is not yet handled by `undetected_chromedriver`. While version Chrome v115 is compatible with Chromedriver v114 (either don't specify a `chrome_version` in your config file or specify it as `114` if you are using Chrome v115), 116+ is not.

There are a few ways to fix this:
1. Download the latest version in the develop branch. To do this, run `git pull && git checkout develop`. Then, make sure to update the dependencies by running `pip install -r requirements.txt`
2. Download the Chromedriver version that corresponds to your Chrome/Chromium version. The driver download may come with browser, but if you don't have it, you can download the latest version [here](https://googlechromelabs.github.io/chrome-for-testing/#stable). Then, make sure to put the location of your download in the `chromedriver_path` in your `config.json` and you are good to go
3. Revert back to Chrome version 115 or older

### To Reproduce

Run this script with Chrome/Chromium versions 116+

**Comment by HsuTimothy** [comment]
Thanks this worked!

**Comment by DougSisk** [comment]
How do you configure it to look for Google Chrome for Testing? I ran both `npx @puppeteer/browsers install chrome@116` and `npx @puppeteer/browsers install chromedriver@116` and set my `chromedriver_path` but it's not working for me at all 😕

**Comment by jdholtz** [comment]
@DougSisk you can download the latest chromedriver from the link I provided in point 1. Then, extract the zip file and the Chromedriver in the extracted folder will be the Chromedriver to point to in `chromedriver_path`

**Comment by DougSisk** [comment]
> @DougSisk you can download the latest chromedriver from the link I provided in point 1. Then, extract the zip file and the Chromedriver in the extracted folder will be the Chromedriver to point to in `chromedriver_path`

Doesn't work for me on MacOS Ventura 13.5.1

```
python3 southwest.py            
Process Process-1:
Traceback (most recent call last):
  File "/Users/doug/Code/auto-southwest-check-in/lib/webdriver.py", line 164, in _init_driver
    driver = Chrome(
             ^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1824, in _execute_child
    and os.path.dirname(executable)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/doug/Code/auto-southwest-check-in/lib/reservation_monitor.py", line 41, in monitor
    self._monitor()
  File "/Users/doug/Code/auto-southwest-check-in/lib/reservation_monitor.py", line 156, in _monitor
    reservations, skip_scheduling = self._get_reservations()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/doug/Code/auto-southwest-check-in/lib/reservation_monitor.py", line 180, in _get_reservations
    reservations = webdriver.get_reservations(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/doug/Code/auto-southwest-check-in/lib/webdriver.py", line 89, in get_reservations
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/doug/Code/auto-southwest-check-in/lib/webdriver.py", line 139, in _get_driver
    driver = self._init_driver()
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/doug/Code/auto-southwest-check-in/lib/webdriver.py", line 181, in _init_driver
    raise RuntimeError(
RuntimeError: Failed to initialize the webdriver after 3 attempts
```

**Comment by jdholtz** [comment]
@DougSisk you may need to try the x64 version for Mac (people had issues with the arm version) and install Rosetta. Alternatively, you can use the Docker image which is not prone to this problem. 

Also, what path are you putting in? It doesn’t seem to be able to find the chromedriver.

**Comment by DougSisk** [comment]
I've got it running on Docker now.

Quickly tried downloading the x64 version and same error. Have the full path in my config:
```
{
    "check_fares": true,
    "chrome_version": 116,
    "chromedriver_path": "/Users/doug/chromedriver-mac-x64/chromedriver",
    "notification_urls": "tgram://REDACTED",
    "notification_level": 1,
    "retrieval_interval": 24,
    "accounts": [
        {
            "username": "REDACTED",
            "password": "REDACTED"
        }
    ]
}
```

**Comment by jdholtz** [comment]
Hey @DougSisk, my PR to fix this issue was just merged in undetected_chromedriver. Could you try using the develop branch (`git pull && git checkout develop`)? There are a few other things you need to do:
1. Install the requirements with `pip install -r requirements.txt`
2. Install the new undetected_chromedriver version with `pip install -U undetected_chromedriver`
3. Remove the `chromedriver_path` from your config.json and try again

This would help ensure this is not an issue anymore in the latest version of undetected chromedriver

**Comment by DougSisk** [comment]
Now working 👏  Thanks!!

**Comment by jdholtz** [comment]
Great to hear! Thanks for helping troubleshoot
