### ISSUE TITLE
airport_timezones.json Error

### ISSUE THREAD

**Issue by pltrant** [jdholtz/auto-southwest-check-in#14]
I'm suddenly getting this error. I do have the most current version downloaded.  This is on Windows 11 (22H2) with Python 3.10.5.

```
C:\>python "C:\auto-southwest-check-in\southwest.py" 14MNE6 Soandso Person
Traceback (most recent call last):
  File "C:\auto-southwest-check-in\southwest.py", line 33, in <module>
    set_up(arguments)
  File "C:\auto-southwest-check-in\southwest.py", line 24, in set_up
    account.get_checkin_info(confirmation_number)
  File "C:\auto-southwest-check-in\lib\account.py", line 45, in get_checkin_info
    self._get_reservation_info(confirmation_number)
  File "C:\auto-southwest-check-in\lib\account.py", line 73, in _get_reservation_info
    flight = Flight(self, confirmation_number, flight)
  File "C:\auto-southwest-check-in\lib\flight.py", line 25, in __init__
    self._get_flight_info(flight)
  File "C:\auto-southwest-check-in\lib\flight.py", line 32, in _get_flight_info
    self.departure_time = self._get_flight_time(flight)
  File "C:\auto-southwest-check-in\lib\flight.py", line 37, in _get_flight_time
    airport_timezone = self._get_airport_timezone(departure_airport_code)
  File "C:\auto-southwest-check-in\lib\flight.py", line 44, in _get_airport_timezone
    with open("utils/airport_timezones.json") as tz:
FileNotFoundError: [Errno 2] No such file or directory: 'utils/airport_timezones.json'
```
\auto-southwest-check-in\utils\airport_timezones.json does exist too.

**Comment by pltrant** [comment]
This fixes it on Windows, but I'm not sure about linux:

_get_airport_timezone in flight.py:
```
script_dir = os.path.dirname(__file__)
tz_file_path = '..\\utils\\airport_timezones.json'
with open(os.path.join(script_dir, tz_file_path)) as tz:
```

**Comment by jdholtz** [comment]
Thanks for bringing this to my attention. I forgot to test on Windows. I’ll try to integrate your potential fix to work on both systems.

**Comment by jdholtz** [comment]
Hey @pltrant. I've provided a potential fix in the [absolute_paths](https://github.com/jdholtz/auto-southwest-check-in/tree/absolute_paths) branch. Can you test this to make sure it works in Windows (python should handle it, but just to be sure)?

P.S your Check In information is in the picture you provided. You may want to remove that

**Comment by pltrant** [comment]
Confirmed, this resolved the issue!

[The check in information from my original post were modified . That's not the real information . Thanks though!]
