### ISSUE TITLE
RuntimeError: Failed to initialize the webdriver after 3 attempts

### ISSUE THREAD

**Issue by clwclw123** [jdholtz/auto-southwest-check-in#143]
### Version

Auto-Southwest Check-In v5.1

### Description

```

C:\Users\user\Desktop\auto-southwest-check-in>python3 southwest.py userswa password1 --verbose
2023-08-31 17:09:26 DEBUG MainProcess[log:23]: Initialized the application
2023-08-31 17:09:26 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v5.1
2023-08-31 17:09:26 DEBUG MainProcess[main:113]: Called with 2 arguments
2023-08-31 17:09:27 DEBUG MainProcess[config:110]: Initializing configuration file
2023-08-31 17:09:27 DEBUG MainProcess[config:138]: Reading the configuration file
2023-08-31 17:09:27 DEBUG MainProcess[config:58]: Setting check fares to False
2023-08-31 17:09:27 DEBUG MainProcess[config:70]: Setting notification level to <NotificationLevel.INFO: 1>
2023-08-31 17:09:27 DEBUG MainProcess[config:83]: Using 0 notification services
2023-08-31 17:09:27 DEBUG MainProcess[config:87]: Setting retrieval interval to 24 hours
2023-08-31 17:09:27 DEBUG MainProcess[config:121]: Creating configurations for 0 accounts
2023-08-31 17:09:27 DEBUG MainProcess[config:128]: Creating configurations for 0 reservations
2023-08-31 17:09:27 DEBUG MainProcess[config:121]: Creating configurations for 1 accounts
2023-08-31 17:09:27 DEBUG MainProcess[main:129]: Account added through CLI arguments
2023-08-31 17:09:27 DEBUG MainProcess[main:142]: Monitoring 1 accounts and 0 reservations
2023-08-31 17:09:30 DEBUG Process-1[reservation_monitor:154]: Acquiring lock...
2023-08-31 17:09:30 DEBUG Process-1[reservation_monitor:156]: Lock acquired
2023-08-31 17:09:30 DEBUG Process-1[reservation_monitor:178]: Retrieving reservations for account
2023-08-31 17:09:30 DEBUG Process-1[webdriver:146]: Starting webdriver for current session
2023-08-31 17:09:32 DEBUG Process-1[webdriver:180]: An exception occurred when initializing the webdriver: Name: TypeError. Error: Binary Location Must be a String
2023-08-31 17:09:32 DEBUG Process-1[webdriver:186]: 2 more attempts
2023-08-31 17:09:34 DEBUG Process-1[webdriver:180]: An exception occurred when initializing the webdriver: Name: TypeError. Error: Binary Location Must be a String
2023-08-31 17:09:34 DEBUG Process-1[webdriver:186]: 1 more attempts
2023-08-31 17:09:37 DEBUG Process-1[webdriver:180]: An exception occurred when initializing the webdriver: Name: TypeError. Error: Binary Location Must be a String
2023-08-31 17:09:37 DEBUG Process-1[webdriver:186]: 0 more attempts
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\webdriver.py", line 172, in _init_driver
    driver = Chrome(
             ^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\undetected_chromedriver\__init__.py", line 372, in __init__
    options.binary_location = (
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\chromium\options.py", line 55, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 157, in _monitor
    reservations, skip_scheduling = self._get_reservations()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\reservation_monitor.py", line 182, in _get_reservations
    reservations = webdriver.get_reservations(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\webdriver.py", line 95, in get_reservations
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\webdriver.py", line 147, in _get_driver
    driver = self._init_driver()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\auto-southwest-check-in\lib\webdriver.py", line 189, in _init_driver
    raise RuntimeError(
RuntimeError: Failed to initialize the webdriver after 3 attempts

C:\Users\user\Desktop\auto-southwest-check-in>
```

### To Reproduce

python3 southwest.py userswa password1 --verbose

**Comment by jdholtz** [comment]
Hey @clwclw123, I believe this means you don't have Chrome installed on your machine. Can you try to install Chrome (or a Chromium-based browser) or use the Docker image to see if that fixes your issue?

**Comment by jdholtz** [comment]
> (I have Edge and Brave which are Chromium based browsers, but it didn't work)

Good to know. This may be fixed by being able to provide the browser's executable path in `config.json`. Would you want me to make the change so you don't have to have Chrome (Chromium also works)?

**Comment by jdholtz** [comment]
You can now add Brave's executable path to the config.json (see the Configuration doc for details) in the `develop` branch. Unfortunately, Microsoft Edge is not supported by `undetected_chromedriver`, so it won't work.
