### ISSUE TITLE
Python script fails to launch

### ISSUE THREAD

**Issue by manny33** [jdholtz/auto-southwest-check-in#168]
### Version

6.1

### Description

the python script fails to launch and throws a traceback

### To Reproduce

1. git clone https://github.com/jdholtz/auto-southwest-check-in.git
2. cd auto-southwest-check-in
3. python3 -m venv venv
4. source venv/bin/activate
5. pip install -r requirements.txt
6. python3 southwest.py CONFIRMATION_NUMBER FIRST_NAME LAST_NAME

### Expected Behavior

Doesn't crash

### Relevant logs and program output

```sh
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/raster/swcheckin/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/home/raster/swcheckin/auto-southwest-check-in/lib/reservation_monitor.py", line 65, in _monitor
    self.checkin_scheduler.refresh_headers()
  File "/home/raster/swcheckin/auto-southwest-check-in/lib/checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "/home/raster/swcheckin/auto-southwest-check-in/lib/webdriver.py", line 63, in set_headers
    driver = self._get_driver()
  File "/home/raster/swcheckin/auto-southwest-check-in/lib/webdriver.py", line 126, in _get_driver
    driver = Driver(
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 417, in Driver
    driver = browser_launcher.get_driver(
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1414, in get_driver
    return get_local_driver(
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3108, in get_local_driver
    driver = undetected.Chrome(
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 221, in __init__
    options.binary_location = (
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py", line 55, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String
```

### Additional context

I'm running on a headless linux machine. Ubuntu LTS 22.04.

**Comment by manny33** [comment]
The docker image also failed on this server. But i did try the docker image in another server (running manjaro) i have that does have an X session running. That worked fine. I haven't tried the python path on this server

**Comment by jdholtz** [comment]
Do you have the `browser_path` in your config.json?

If not, can you try debugging in the Python terminal? Execute `python` and then enter the following in the Python terminal to see if the same error is reached.
```py
from seleniumbase import Driver
driver = Driver(undetectable=True, headless=True, uc_cdp_events=True)  # <-- Does it error here?
```

If that still errors, can you upgrade SeleniumBase (`pip install --upgrade seleniumbase`) and see if you reach the same error in the script?

**Comment by manny33** [comment]
I dont' have a config.json, and issuing the python commands does yield an error. 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 417, in Driver
    driver = browser_launcher.get_driver(
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1414, in get_driver
    return get_local_driver(
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3108, in get_local_driver
    driver = undetected.Chrome(
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 221, in __init__
    options.binary_location = (
  File "/home/raster/swcheckin/auto-southwest-check-in/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py", line 55, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String

**Comment by jdholtz** [comment]
Do you have Chrome (or a Chromium-based browser installed)? You said that the Docker image is still getting errors, which has Chrome installed, so I'm not sure the issue now.

**Comment by manny33** [comment]
I do not have chrome installed on the headless server. 

If i run the docker container with --verbose i get the following output;

> 2023-10-04 17:33:45 DEBUG MainProcess[log:23]: Initialized the application
2023-10-04 17:33:45 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v6.1
2023-10-04 17:33:45 DEBUG MainProcess[main:113]: Called with 3 arguments
2023-10-04 17:33:45 DEBUG MainProcess[config:107]: Initializing configuration file
2023-10-04 17:33:45 DEBUG MainProcess[config:135]: Reading the configuration file
2023-10-04 17:33:45 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-10-04 17:33:45 DEBUG MainProcess[config:125]: Creating configurations for 1 reservations
2023-10-04 17:33:45 DEBUG MainProcess[main:137]: Reservation added through CLI arguments
2023-10-04 17:33:45 DEBUG MainProcess[main:142]: Monitoring 0 accounts and 1 reservations
2023-10-04 17:33:45 DEBUG Process-1[reservation_monitor:60]: Acquiring lock...
2023-10-04 17:33:45 DEBUG Process-1[reservation_monitor:62]: Lock acquired
2023-10-04 17:33:45 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
2023-10-04 17:33:45 DEBUG Process-1[webdriver:124]: Starting webdriver for current session

it just hangs trying to start the webdriver. This is all  the headless server.

**Comment by jdholtz** [comment]
> I do not have chrome installed on the headless server.

A Chromium-based browser is needed to run this script.

> it just hangs trying to start the webdriver. This is all the headless server.

Could you try manually starting the webdriver in the Docker container and see what the issue is? Here are the steps:
1. Run the container for infinite time: `docker run -d --entrypoint sleep jdholtz/auto-southwest-check-in:v6.1 infinity`
2. Exec into the container: `docker exec -it <container_name> sh`
3. In the container enter the Python terminal (type `python`) and enter the following commands:
```py
from seleniumbase import Driver
# It may hang on this next line. Let me know if there is a traceback 
# if it throws one after a minute or two
driver = Driver(headless=True, undetectable=True, uc_cdp_events=True)
driver.get("https://mobile.southwest.com/check-in")

**Comment by cmclinton** [comment]
I switched over to an Amazon EC2 instance just for testing. I'm getting a Binary Location Must be A String error similar to the original error in this thread.

```
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from seleniumbase import Driver
>>> driver = Driver(headless=True,undetectable=True, uc_cdp_events=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/seleniumbase/plugins/driver_manager.py", line 430, in Driver
    driver = browser_launcher.get_driver(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 1432, in get_driver
    return get_local_driver(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/seleniumbase/core/browser_launcher.py", line 3207, in get_local_driver
    driver = undetected.Chrome(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/seleniumbase/undetected/__init__.py", line 221, in __init__
    options.binary_location = (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/options.py", line 52, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String
>>> 
```

**Comment by jdholtz** [comment]
It would be great if you could make an issue in the [SeleniumBase](https://github.com/seleniumbase/SeleniumBase) repository, since it can be reproduced without using this script at all. Just make sure to provide details about the seleniumbase version used, the full traceback, the platform and Python version, as well as the minimum amount of code that makes the issue appear.

**Comment by jdholtz** [comment]
@cmclinton did you install Chrome on that Amazon EC2 instance? Chrome is needed for this script.

**Comment by cmclinton** [comment]
Just installed Chrome on the EC2 instance and southwest.py 6.1 is running correctly. Thanks!

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
```

**Comment by manny33** [comment]
I didn't install chrome native into the server. I don't have snap / flatpak running on that server either, so I'm just using the Manjaro machine i have. didn't want to add packages to the server.

**Comment by manny33** [comment]
PS. 
I'm looking into the docker image. see if chromium is actually there, or if it needs chrome (selenium)

**Comment by manny33** [comment]
@jdholtz if it helps, i changed the dockerfile to be the base 3.11 pyhthon image. Which is debian bookworm based. that did work after getting the chrome repository set up etc. It also makes it a 1.8gb image haha. I wonder if the issue is that selenium can't start a chromium session. 

this is what the dockerfile looks like;

> FROM python:3.11
> 
> WORKDIR /app
> 
> RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub > linux_signing_key.pub
> RUN install -D -o root -g root -m 644 linux_signing_key.pub /etc/apt/keyrings/linux_signing_key.pub
> RUN sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/linux_signing_key.pub] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google->
> RUN apt update
> RUN apt install google-chrome-stable -y
> 
> COPY requirements.txt requirements.txt
> RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt
> 
> RUN sbase get chromedriver
> 
> COPY . .
> 
> ENTRYPOINT ["python3", "-u", "southwest.py"]

**Comment by jdholtz** [comment]
Try running with the `--privileged` flag and see if it works. Some other people have had issues with the webdriver not starting correctly and have fixed it with that flag.

> This does point to an issue with selenium. I'll keep playing around with the alpine image.

I appreciate you taking your time to debug this!

**Comment by jdholtz** [comment]
Hey @manny33, do you have any updates on whether running the script with `--privileged` works?

**Comment by manny33** [comment]
adding --cap-add=SYS_ADMIN also makes it work. NET_ADMIN does not.

**Comment by jdholtz** [comment]
This is actually the same issue as #147 then. Some people reported not needing the flag/capability after some time (although, a specific fix was never found). What I can do is add this to the FAQ so people running into this same issue in the future can fix this. 

It isn’t a great fix, but since I’m not able to reproduce it and people have reported that the issue eventually goes away, that’ll be the accepted solution for now (unless someone comes up with a better fix).
