### ISSUE TITLE
Docker image not working on ARM architecture

### ISSUE THREAD

**Issue by jmselk** [jdholtz/auto-southwest-check-in#177]
### Version

Docker image d770fab909d9

### Description

Using the latest docker image (d770fab909d9) on OSX with an M1

```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory

Warning: uc_driver not found. Getting it now:

*** chromedriver to download = 117.0.5938.149 (Previous Version)

Downloading chromedriver-linux64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.149/linux64/chromedriver-linux64.zip ...
Download Complete!

Extracting ['chromedriver'] from chromedriver-linux64.zip ...
Unzip Complete!

The file [uc_driver] was saved to:
/usr/local/lib/python3.11/site-packages/seleniumbase/drivers/uc_driver

Making [uc_driver 117.0.5938.149] executable ...
[uc_driver 117.0.5938.149] is now ready for use!

Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/app/lib/reservation_monitor.py", line 65, in _monitor
    self.checkin_scheduler.refresh_headers()
  File "/app/lib/checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "/app/lib/webdriver.py", line 63, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/app/lib/webdriver.py", line 126, in _get_driver
    driver = Driver(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/plugins/driver_manager.py", line 417, in Driver
    driver = browser_launcher.get_driver(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 1414, in get_driver
    return get_local_driver(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3108, in get_local_driver
    driver = undetected.Chrome(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 307, in __init__
    super().__init__(options=options, service=service_)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 53, in __init__
    self.service.start()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 109, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 122, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/lib/python3.11/site-packages/seleniumbase/drivers/uc_driver unexpectedly exited. Status code was: 255
```

### To Reproduce

docker pull jdholtz/auto-southwest-check-in
docker run jdholtz/auto-southwest-check-in CONF_CODE FIRST_NAME LAST_NAME

**Comment by jdholtz** [comment]
I'm having trouble getting the Docker image to work on ARM in v6.1 too. I'll look into it and see if I can find a solution.

**Comment by jdholtz** [comment]
This should now be fixed in the latest commit of the develop branch (you can pull the Docker image with the `:develop` tag to test). I tested on a Raspberry Pi (ARM architecture) and it successfully checked in to a flight with the newest fix.
