### ISSUE TITLE
SSL Certificate Error When Downloading Chromedriver

### ISSUE THREAD

**Issue by ducktapeonmydesk** [jdholtz/auto-southwest-check-in#186]
### Version

7.1

### Browser Version

119.0.6045.160

### Description

Getting the error 'WebDriver' object has no attribute 'add_cdp_listener'.  I've looked at other open issues, such as #180.  I've switched to the develop branch and still cannot overcome that error.

### To Reproduce

Run _py southwest.py Confirmation# First Last_

### Additional context

I've got it working on WSL on the develop branch.  However, it will not work on windows, neither running the code in a virtual environment (venv) nor running the docker container.

**Comment by jdholtz** [comment]
What is the output of the command `sbase get uc_driver mlatest`? The issue is that the newest Chromedriver version isn’t out yet, but that should have been mitigated in v7.1

**Comment by ducktapeonmydesk** [comment]
> ~What is the output of the command `sbase get uc_driver mlatest`?~ Nevermind, this is not supported.
> 
> The issue is that the newest Chromedriver version isn’t out yet, but that should have been mitigated in v7.1
> 
> > nor running the docker container
> 
> That's strange that it isn't working in Docker. Can you send the output of running the script in verbose mode in both Docker and your Windows environment?
> 
> If you run `sbase get uc_driver latest` in your virtual environment and run the script afterwards, does that fix the issue?

Output from `sbase get uc_driver latest`

`
*** chromedriver to download = 114.0.5735.90 (Legacy Version)

Downloading chromedriver_win32.zip from:
https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver_win32.zip ...
Unzip Complete!

The file [uc_driver.exe] was saved to:
C:\Users\warrenj\Source\Southwest\.env\Lib\site-packages\seleniumbase\drivers\uc_driver.exe

Making [uc_driver.exe 114.0.5735.90] executable ...
[uc_driver.exe 114.0.5735.90] is now ready for use!
`

Output from running in virtual environment
`
2023-11-15 09:27:59 DEBUG MainProcess[log:23]: Initialized the application
2023-11-15 09:27:59 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.1
2023-11-15 09:27:59 DEBUG MainProcess[main:113]: Called with 3 arguments
2023-11-15 09:27:59 DEBUG MainProcess[config:107]: Initializing configuration file
2023-11-15 09:27:59 DEBUG MainProcess[config:135]: Reading the configuration file
2023-11-15 09:27:59 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-11-15 09:27:59 DEBUG MainProcess[config:125]: Creating configurations for 1 reservations
2023-11-15 09:27:59 DEBUG MainProcess[main:137]: Reservation added through CLI arguments
2023-11-15 09:27:59 DEBUG MainProcess[main:142]: Monitoring 0 accounts and 1 reservations
2023-11-15 09:28:00 DEBUG Process-1[reservation_monitor:60]: Acquiring lock...
2023-11-15 09:28:00 DEBUG Process-1[reservation_monitor:62]: Lock acquired
2023-11-15 09:28:00 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
2023-11-15 09:28:00 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
2023-11-15 09:28:02 DEBUG Process-1[webdriver:119]: Using browser version: 119.0.6045.160
Process Process-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\auto-southwest-check-in\lib\reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\auto-southwest-check-in\lib\reservation_monitor.py", line 65, in _monitor
    self.checkin_scheduler.refresh_headers()
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\auto-southwest-check-in\lib\checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\auto-southwest-check-in\lib\webdriver.py", line 64, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\auto-southwest-check-in\lib\webdriver.py", line 121, in _get_driver
    driver.add_cdp_listener("Network.requestWillBeSent", self._headers_listener)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'
`

Running the docker container (I am running the latest, _not_ the develop branch)
`
2023-11-15 15:31:49 DEBUG MainProcess[log:23]: Initialized the application
2023-11-15 15:31:49 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.1
2023-11-15 15:31:49 DEBUG MainProcess[main:113]: Called with 3 arguments
2023-11-15 15:31:49 DEBUG MainProcess[config:107]: Initializing configuration file
2023-11-15 15:31:49 DEBUG MainProcess[config:135]: Reading the configuration file
2023-11-15 15:31:49 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-11-15 15:31:49 DEBUG MainProcess[config:125]: Creating configurations for 1 reservations
2023-11-15 15:31:49 DEBUG MainProcess[main:137]: Reservation added through CLI arguments
2023-11-15 15:31:49 DEBUG MainProcess[main:142]: Monitoring 0 accounts and 1 reservations
2023-11-15 15:31:50 DEBUG Process-1[reservation_monitor:60]: Acquiring lock...
2023-11-15 15:31:50 DEBUG Process-1[reservation_monitor:62]: Lock acquired
2023-11-15 15:31:50 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
2023-11-15 15:31:50 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
2023-11-15 15:31:51 DEBUG Process-1[webdriver:119]: Using browser version: 117.0.5938.62
2023-11-15 15:31:51 DEBUG Process-1[webdriver:123]: Loading Southwest Check-In page
2023-11-15 15:31:52 DEBUG Process-1[webdriver:65]: Waiting for valid headers
2023-11-15 15:31:52 DEBUG Process-1[webdriver:152]: Waiting for headers_set to be set
`
The docker container just hangs here.

**Comment by jdholtz** [comment]
> `*** chromedriver to download = 114.0.5735.90 (Legacy Version)

SeleniumBase is downloading a very old version of Chromedriver for some reason. Could you try downloading the newest Chromedriver with `sbase get uc_driver 119.0.6045.105`? You may need to replace the full version with just 119 if it doesn’t work.

**Comment by ducktapeonmydesk** [comment]
> > `*** chromedriver to download = 114.0.5735.90 (Legacy Version)
> 
> SeleniumBase is downloading a very old version of Chromedriver for some reason. Could you try downloading the newest Chromedriver with `sbase get uc_driver 119.0.6045.105`? You may need to replace the full version with just 119 if it doesn’t work.

This is what I get:

```

* Unable to download driver! Retrying in 3s...

** Unable to download driver! Retrying in 5s...

Traceback (most recent call last):
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/known-good-versions.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\seleniumbase\console_scripts\sb_install.py", line 139, in requests_get
    response = requests.get(url, proxies=proxies, timeout=1.25)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/known-good-versions.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\util\ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\util\ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/known-good-versions.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\scripts\sbase.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\seleniumbase\console_scripts\run.py", line 1015, in main
    sb_install.main()
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\seleniumbase\console_scripts\sb_install.py", line 455, in main
    url_request = get_cft_known_good_versions()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\seleniumbase\console_scripts\sb_install.py", line 173, in get_cft_known_good_versions
    sb_config.cft_kgv_json = requests_get(cft_ngv_url)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\seleniumbase\console_scripts\sb_install.py", line 144, in requests_get
    response = requests.get(url, proxies=proxies, timeout=2.75)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\sessions.py", line 725, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\sessions.py", line 266, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ducktapeonmydesk\Source\Southwest\.env\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/known-good-versions.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))
```

**Comment by jdholtz** [comment]
> .SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The underlying issue is this, which is why SeleniumBase is downloading an old version of Chromedriver, hence why you are getting the attribute error. 

I pasted that error into Google and focused on issues for Windows, but haven’t been able to find anything that may help your situation. Since it also happens in Docker, it may be an issue with your network (similar to #169). I recommend that you look up that error and try any suggestions. Since the issue applies more broadly than just the script and is specific to your system, I won’t be able to provide much further help to fix this.

**Comment by ducktapeonmydesk** [comment]
> > .SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
> 
> The underlying issue is this, which is why SeleniumBase is downloading an old version of Chromedriver, hence why you are getting the attribute error.
> 
> I pasted that error into Google and focused on issues for Windows, but haven’t been able to find anything that may help your situation. Since it also happens in Docker, it may be an issue with your network (similar to #169). I recommend that you look up that error and try any suggestions. Since the issue applies more broadly than just the script and is specific to your system, I won’t be able to provide much further help to fix this.

No worries, I appreciate the help!

**Comment by jdholtz** [comment]
Let me know if you end up fixing it because it might be helpful for others running into the same issue too
