### ISSUE TITLE
Two Check-ins running at same time fails

### ISSUE THREAD

**Issue by fergiedrew** [jdholtz/auto-southwest-check-in#197]
### Version

Auto-Southwest Check-In v7.1

### Browser Version

chrome=120.0.6099.71

### Description

I ran this script on two terminals for my brother and I on the same laptop. I have done this successfully before, but this time I received this message for my brother: 

```
Successfully scheduled the following flights to check in for Austin Ferguson:
Flight from Dallas (Love Field) to Washington (Reagan National) at 2023-12-22 22:55:00 UTC
Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/checkin_handler.py", line 72, in _set_check_in
    self._wait_for_check_in(checkin_time)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/checkin_handler.py", line 97, in _wait_for_check_in
    self.checkin_scheduler.refresh_headers()
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/webdriver.py", line 64, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/webdriver.py", line 124, in _get_driver
    driver.get(CHECKIN_URL)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3556, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 391, in uc_special_open_if_cf
    driver.default_get(url)  # The original one
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 373, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=120.0.6099.71)
Stacktrace:
#0 0x560649fc6f83 <unknown>
#1 0x560649c7fcf7 <unknown>
#2 0x560649c657a1 <unknown>
#3 0x560649c6544a <unknown>
#4 0x560649c637e1 <unknown>
#5 0x560649c6401a <unknown>
#6 0x560649c82bbe <unknown>
#7 0x560649d187a5 <unknown>
#8 0x560649cf90b2 <unknown>
#9 0x560649d18006 <unknown>
#10 0x560649cf8e53 <unknown>
#11 0x560649cc0dd4 <unknown>
#12 0x560649cc21de <unknown>
#13 0x560649f8b531 <unknown>
#14 0x560649f8f455 <unknown>
#15 0x560649f77f55 <unknown>
#16 0x560649f900ef <unknown>
#17 0x560649f5b99f <unknown>
#18 0x560649fb4008 <unknown>
#19 0x560649fb41d7 <unknown>
#20 0x560649fc6124 <unknown>
#21 0x7fa7d928f6ba <unknown>

```

### To Reproduce

1. Run script on for two people on same computer
2. One of them seems to fail, perhaps due to doing them at the same time.

### Expected Behavior

Both people should have been checked in.

### Relevant logs and program output

```sh
Successfully scheduled the following flights to check in for Austin Ferguson:
Flight from Dallas (Love Field) to Washington (Reagan National) at 2023-12-22 22:55:00 UTC
Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/checkin_handler.py", line 72, in _set_check_in
    self._wait_for_check_in(checkin_time)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/checkin_handler.py", line 97, in _wait_for_check_in
    self.checkin_scheduler.refresh_headers()
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/webdriver.py", line 64, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/lib/webdriver.py", line 124, in _get_driver
    driver.get(CHECKIN_URL)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 3556, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/seleniumbase/core/browser_launcher.py", line 391, in uc_special_open_if_cf
    driver.default_get(url)  # The original one
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/seleniumbase/undetected/__init__.py", line 373, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/cool-andy/Documents/Playground/Cool Convenience Scripts/auto-southwest-check-in/env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: Unable to receive message from renderer
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=120.0.6099.71)
Stacktrace:
#0 0x560649fc6f83 <unknown>
#1 0x560649c7fcf7 <unknown>
#2 0x560649c657a1 <unknown>
#3 0x560649c6544a <unknown>
#4 0x560649c637e1 <unknown>
#5 0x560649c6401a <unknown>
#6 0x560649c82bbe <unknown>
#7 0x560649d187a5 <unknown>
#8 0x560649cf90b2 <unknown>
#9 0x560649d18006 <unknown>
#10 0x560649cf8e53 <unknown>
#11 0x560649cc0dd4 <unknown>
#12 0x560649cc21de <unknown>
#13 0x560649f8b531 <unknown>
#14 0x560649f8f455 <unknown>
#15 0x560649f77f55 <unknown>
#16 0x560649f900ef <unknown>
#17 0x560649f5b99f <unknown>
#18 0x560649fb4008 <unknown>
#19 0x560649fb41d7 <unknown>
#20 0x560649fc6124 <unknown>
#21 0x7fa7d928f6ba <unknown>
```

**Comment by jdholtz** [comment]
Hi. Thanks for reporting this issue. Can you send the log file of the runs? It is in the `logs/` directory.

Is there a reason you were running two different instances of the script? There is functionality within the script to prevent two accounts from using Chrome at the same time, but running two separate instances will not prevent this.

Therefore, I don't think there is good reason to support this, as it is already handled if one instance of the script is run with multiple reservations/accounts. If, for some reason, you want to run two instances of the script, I recommend you use two Docker containers as that will prevent the scripts from colliding.

**Comment by fergiedrew** [comment]
Yeah, here's the cat: 


```
➜  logs git:(master) ✗ cat auto-southwest-check-in.log.2
2023-12-21 15:22:55 DEBUG MainProcess[log:23]: Initialized the application
2023-12-21 15:22:55 DEBUG MainProcess[main:112]: Auto-Southwest Check-In v7.1
2023-12-21 15:22:55 DEBUG MainProcess[main:113]: Called with 3 arguments
2023-12-21 15:22:55 DEBUG MainProcess[config:107]: Initializing configuration file
2023-12-21 15:22:55 DEBUG MainProcess[config:135]: Reading the configuration file
2023-12-21 15:22:55 DEBUG MainProcess[config:139]: No configuration file found. Using defaults
2023-12-21 15:22:55 DEBUG MainProcess[config:125]: Creating configurations for 1 reservations
2023-12-21 15:22:55 DEBUG MainProcess[main:137]: Reservation added through CLI arguments
2023-12-21 15:22:55 DEBUG MainProcess[main:142]: Monitoring 0 accounts and 1 reservations
2023-12-21 15:22:55 DEBUG Process-1[reservation_monitor:60]: Acquiring lock...
2023-12-21 15:22:55 DEBUG Process-1[reservation_monitor:62]: Lock acquired
2023-12-21 15:22:55 DEBUG Process-1[checkin_scheduler:50]: Refreshing headers for current session
2023-12-21 15:22:55 DEBUG Process-1[webdriver:103]: Starting webdriver for current session
2023-12-21 15:22:57 DEBUG Process-1[webdriver:119]: Using browser version: 120.0.6099.71
2023-12-21 15:22:57 DEBUG Process-1[webdriver:123]: Loading Southwest Check-In page
2023-12-21 15:23:02 DEBUG Process-1[webdriver:65]: Waiting for valid headers
2023-12-21 15:23:02 DEBUG Process-1[webdriver:152]: Waiting for headers_set to be set
2023-12-21 15:23:03 DEBUG Process-1[webdriver:156]: headers_set set successfully
2023-12-21 15:23:03 DEBUG Process-1[reservation_monitor:84]: Scheduling flight check-ins for 1 reservations
2023-12-21 15:23:03 DEBUG Process-1[checkin_scheduler:76]: Retrieving reservation information
2023-12-21 15:23:04 DEBUG Process-1[utils:34]: Successfully made request after 1 attempts
2023-12-21 15:23:04 DEBUG Process-1[checkin_scheduler:89]: Successfully retrieved reservation information
2023-12-21 15:23:04 DEBUG Process-1[checkin_scheduler:57]: 1 flights found under current reservation
2023-12-21 15:23:04 DEBUG Process-1[checkin_scheduler:43]: 1 total flights were found
2023-12-21 15:23:04 DEBUG Process-1[checkin_scheduler:100]: 1 new flights found
2023-12-21 15:23:04 DEBUG Process-1[checkin_scheduler:104]: Scheduling 1 flights for check-in
2023-12-21 15:23:04 DEBUG Process-1[checkin_handler:41]: Scheduling check-in for current flight
2023-12-21 15:23:05 DEBUG Process-1[notification_handler:66]: Sending new flights notification
2023-12-21 15:23:05 DEBUG Process-1:1[checkin_handler:89]: Sleeping until thirty minutes before check-in...
2023-12-21 15:23:05 DEBUG Process-1[checkin_scheduler:116]: 1 flights are currently scheduled. Removing old flights
2023-12-21 15:23:05 DEBUG Process-1[checkin_scheduler:132]: Successfully removed old flights. 1 flights are now scheduled
2023-12-21 15:23:05 DEBUG Process-1[reservation_monitor:93]: Checking fares for 1 flights
2023-12-21 15:23:05 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2023-12-21 15:23:05 DEBUG Process-1[fare_checker:88]: Fetching reservation information
2023-12-21 15:23:06 DEBUG Process-1[utils:34]: Successfully made request after 1 attempts
2023-12-21 15:23:06 DEBUG Process-1[fare_checker:103]: Retrieving search information for the current flight
2023-12-21 15:23:07 DEBUG Process-1[utils:34]: Successfully made request after 1 attempts
2023-12-21 15:23:07 DEBUG Process-1[fare_checker:82]: Retrieving matching flights
2023-12-21 15:23:10 DEBUG Process-1[utils:34]: Successfully made request after 1 attempts
2023-12-21 15:23:10 DEBUG Process-1[fare_checker:50]: Found 17 matching flights
2023-12-21 15:23:10 DEBUG Process-1[fare_checker:37]: Flight price change found for 0 PTS
2023-12-21 15:23:10 DEBUG Process-1[reservation_monitor:80]: Lock released
2023-12-21 15:23:10 DEBUG Process-1[reservation_monitor:116]: Sleeping for 86385 seconds
2023-12-21 16:24:55 DEBUG Process-1:1[checkin_handler:94]: Acquiring lock...
2023-12-21 16:24:55 DEBUG Process-1:1[checkin_handler:96]: Lock acquired
2023-12-21 16:24:55 DEBUG Process-1:1[checkin_scheduler:50]: Refreshing headers for current session
2023-12-21 16:24:55 DEBUG Process-1:1[webdriver:103]: Starting webdriver for current session
2023-12-21 16:24:56 DEBUG Process-1:1[webdriver:119]: Using browser version: 120.0.6099.71
2023-12-21 16:24:56 DEBUG Process-1:1[webdriver:123]: Loading Southwest Check-In page
2023-12-21 16:56:37 INFO MainProcess[main:167]: 
Ctrl+C pressed. Stopping all check-ins
2023-12-21 16:56:37 DEBUG Process-1[checkin_handler:52]: Stopping check-in for current flight
2023-12-21 16:56:37 DEBUG Process-1[checkin_handler:55]: Killing process with PID 6011
2023-12-21 16:56:37 DEBUG Process-1[checkin_handler:59]: Waiting for process with PID 6011 to be terminated
2023-12-21 16:56:37 DEBUG Process-1[checkin_handler:65]: Process with PID 6011 successfully terminated
```

**Comment by jdholtz** [comment]
Okay, so it doesn’t look like anything is abnormal in the logs. As said above, I just recommend to run the two accounts in the same script or run them each in their own separate Docker containers to prevent any possible collision like this.

**Comment by jdholtz** [comment]
Hey @fergiedrew, any comments to my above question [here](https://github.com/jdholtz/auto-southwest-check-in/issues/197#issuecomment-1867045931)?

**Comment by fergiedrew** [comment]
That answers my question, I'll probably make use of a docker container in the future. I didn't know I could do multiple reservations while running one script, and I don't see it in the docs. How do I do that?

**Comment by jdholtz** [comment]
> How do I do that?

It is [here](https://github.com/jdholtz/auto-southwest-check-in/blob/master/CONFIGURATION.md#accounts-and-reservations) in the configuration doc.

If you use multiple reservations/accounts on one script, you don’t need to use a Docker container (but it definitely increases reliability and is easier to upgrade).

Thanks for sending the logs and helping debug the issue!
