### ISSUE TITLE
different confirmation same flight.

### ISSUE THREAD

**Issue by ryanjchan** [jdholtz/auto-southwest-check-in#2]
There might be an issue when you try to schedule 2 flights (2 different confirmations) for the same flight on the same system. When each respective thread wakes from its sleep (minus 10) to get its headers, I suspect they hit a race condition since both need chromedriver to get the headers.

```Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryanxfjw/projects/checkin/jdholtz/auto-southwest-check-in/lib/flight.py", line 74, in _set_check_in
    self.account.get_checkin_info(self.confirmation_number)
  File "/home/ryanxfjw/projects/checkin/jdholtz/auto-southwest-check-in/lib/account.py", line 35, in get_checkin_info
    self.headers = webdriver.get_info()
  File "/home/ryanxfjw/projects/checkin/jdholtz/auto-southwest-check-in/lib/webdriver.py", line 29, in get_info
    driver = Chrome(options=options, seleniumwire_options=seleniumwire_options)
  File "/home/ryanxfjw/projects/checkin/jdholtz/auto-southwest-check-in/py37-venv/lib/python3.7/site-packages/seleniumwire/undetected_chromedriver/v2.py", line 55, in __init__
    super().__init__(*args, **kwargs)
  File "/home/ryanxfjw/projects/checkin/jdholtz/auto-southwest-check-in/py37-venv/lib/python3.7/site-packages/undetected_chromedriver/v2.py", line 163, in __init__
    patcher.auto()
  File "/home/ryanxfjw/projects/checkin/jdholtz/auto-southwest-check-in/py37-venv/lib/python3.7/site-packages/undetected_chromedriver/patcher.py", line 121, in auto
    self.unzip_package(self.fetch_package())
  File "/home/ryanxfjw/projects/checkin/jdholtz/auto-southwest-check-in/py37-venv/lib/python3.7/site-packages/undetected_chromedriver/patcher.py", line 175, in unzip_package
    zf.extract(self.exe_name, os.path.dirname(self.executable_path))
  File "/usr/local/lib/python3.7/zipfile.py", line 1619, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python3.7/zipfile.py", line 1690, in _extract_member
    open(targetpath, "wb") as target:
OSError: [Errno 26] Text file busy: '/home/ryanxfjw/.local/share/undetected_chromedriver/chromedriver'
```

I added another random sleep after the initial sleep to hopefully avoid a race condition accessing chromedriver.
```
@@ -67,7 +67,10 @@ class Flight:
             # Only try to refresh the headers if the checkin is more than ten minutes away
             if sleep_time > 0:
                 time.sleep(sleep_time)
-
+                random.seed()
+                t = random.randrange(0,60)
+                time.sleep(t)
```
Since this is an uncommon situation I can't confirm if this quick fix works or not.

**Comment by jdholtz** [comment]
This seems to be an issue other people have experienced using undetected_chromedriver as well. Thanks for being this to my attention. I’ll look to see if there is a fix. 

It seems that your fix would work just fine. However, I’ll look for a better solution, but you can use that in the mean time.

**Comment by jdholtz** [comment]
I was able to reproduce this error easily by just starting two scripts at the same time. Luckily it was an easy fix since this issue got fixed in the latest version of the undetected_chromedriver package
