### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'

### ISSUE THREAD

**Issue by JosephValle** [jdholtz/auto-southwest-check-in#233]
### Version

Auto-Southwest Check-In v7.2

### Browser Version

*** chromedriver to download = 122.0.6261.94 (Latest Stable) 

### Description

Hi,

I an unable to run the check-in on a flight check-in that is today due to this error. Tried it on mac and windows both with chrome installed on them.

### To Reproduce

auto-southwest-check-in % python3 southwest.py CONF FIRST LAST

### Relevant logs and program output

```sh
ownloading chromedriver-mac-x64.zip from:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.94/mac-x64/chromedriver-mac-x64.zip ...
Download Complete!

Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/joseph/auto-southwest-check-in/lib/reservation_monitor.py", line 42, in monitor
    self._monitor()
  File "/Users/joseph/auto-southwest-check-in/lib/reservation_monitor.py", line 65, in _monitor
    self.checkin_scheduler.refresh_headers()
  File "/Users/joseph/auto-southwest-check-in/lib/checkin_scheduler.py", line 52, in refresh_headers
    webdriver.set_headers()
  File "/Users/joseph/auto-southwest-check-in/lib/webdriver.py", line 64, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/joseph/auto-southwest-check-in/lib/webdriver.py", line 121, in _get_driver
    driver.add_cdp_listener("Network.requestWillBeSent", self._headers_listener)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'add_cdp_listener'
```

### Additional context

[auto-southwest-check-in.log](https://github.com/jdholtz/auto-southwest-check-in/files/14450301/auto-southwest-check-in.log)

**Comment by JosephValle** [comment]
Saw the old thread, sorry about that. This command before running did let it work:

git pull && git checkout develop && pip install -r requirements.txt
