### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by babehboi** [jdholtz/auto-southwest-check-in#262]
### Version

7.4

### Browser Version

124.0.6367.207

### Description

Not sure if anyone has been getting this error, but I did a recent pull and tried running both Develop and Master Branch and I get a ModuleNotFound error. In each case two different ones display, despite installing requirements. I even tried recloning. Of course everything was working up until I stopped the script yesterday.

Master: seleniumbase
Develop: ntplib

I've tried looking it up and updating etc, but to no avail. Any thoughts?

### To Reproduce

1. git clone
2. pip install
3. run script

### Relevant logs and program output

```sh
XXX@XXX-ubuntu:~/auto-southwest-check-in$ python southwest.py --verbose
Traceback (most recent call last):
  File "/home/XXX/auto-southwest-check-in/southwest.py", line 59, in <module>
    init(arguments)
  File "/home/XXX/auto-southwest-check-in/southwest.py", line 52, in init
    from lib.main import main
  File "/home/XXX/auto-southwest-check-in/lib/main.py", line 12, in <module>
    from .reservation_monitor import AccountMonitor, ReservationMonitor
  File "/home/XXX/auto-southwest-check-in/lib/reservation_monitor.py", line 7, in <module>
    from .checkin_scheduler import CheckInScheduler
  File "/home/XXX/auto-southwest-check-in/lib/checkin_scheduler.py", line 10, in <module>
    from .webdriver import WebDriver
  File "/home/XXX/auto-southwest-check-in/lib/webdriver.py", line 10, in <module>
    from seleniumbase import Driver
ModuleNotFoundError: No module named 'seleniumbase'
XXX@XXX-ubuntu:~/auto-southwest-check-in$ git switch develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
XXX@XXX-ubuntu:~/auto-southwest-check-in$ python southwest.py --verbose
Traceback (most recent call last):
  File "/home/XXX/auto-southwest-check-in/southwest.py", line 59, in <module>
    init(arguments)
  File "/home/XXX/auto-southwest-check-in/southwest.py", line 52, in init
    from lib.main import main
  File "/home/XXX/auto-southwest-check-in/lib/main.py", line 11, in <module>
    from .config import GlobalConfig, ReservationConfig
  File "/home/XXX/auto-southwest-check-in/lib/config.py", line 8, in <module>
    from .utils import NotificationLevel, is_truthy
  File "/home/XXX/auto-southwest-check-in/lib/utils.py", line 8, in <module>
    import ntplib
ModuleNotFoundError: No module named 'ntplib'
XXX@XXX-ubuntu:~/auto-southwest-check-in$
```

### Additional context

Python 3.11 rc1 / Ubuntu 22.04LTS

**Comment by babehboi** [comment]
Not sure what went wrong, probably not the script, could be something with the server. I"ll continue troubleshooting it, since I tried a previous version and I'm still getting errors. If you, or anyone has any thoughts, feel free to send them my way.

**Comment by babehboi** [comment]
Weird, figured it out.

I'm sure my environmental variable got screwed up somewhere. Working once again.

**Comment by jdholtz** [comment]
To avoid issues like this, the Readme (and I) highly recommend to use a Python virtualenv to manage the dependencies for the script.
