### ISSUE TITLE
Check-in by account not working

### ISSUE THREAD

**Issue by underqualifieditguy** [jdholtz/auto-southwest-check-in#28]
I am getting a stack trace when I try to use the check-in by account log-in method. I have no issues when I schedule the check-in by confirmation number and first name / last name. Could this possibly have something to do with one of the people on the flight have a lap child associated with them?

`python3 southwest.py USERNAME PASSWORD`

```Traceback (most recent call last):
  File "/home/uig/auto-southwest-check-in/southwest.py", line 41, in <module>
    set_up(arguments)
  File "/home/uig/auto-southwest-check-in/southwest.py", line 24, in set_up
    flight_retriever.monitor_account()
  File "/home/uig/auto-southwest-check-in/lib/flight_retriever.py", line 53, in monitor_account
    flights = self._get_flights()
  File "/home/uig/auto-southwest-check-in/lib/flight_retriever.py", line 65, in _get_flights
    flights = webdriver.get_flights(self)
  File "/home/uig/auto-southwest-check-in/lib/webdriver.py", line 113, in get_flights
    self._set_account_name(flight_retriever, response)
  File "/home/uig/auto-southwest-check-in/lib/webdriver.py", line 149, in _set_account_name
    flight_retriever.first_name = response["customers.userInformation.firstName"]
KeyError: 'customers.userInformation.firstName'

**Comment by jdholtz** [comment]
Hi! This error is occurring because it fails to log in (I think). Have you tried multiple times? Sometimes it will fail and you have to redo it (I’ll make it automatically retry in the future). Also, make sure your login credentials are correct as well.

**Comment by underqualifieditguy** [comment]
I only tried it twice, it failed on the very first attempt. My password does have special characters in it but I put the whole thing in quotes so that shouldn’t be an issue right?

**Comment by underqualifieditguy** [comment]
If I have three people in the flight and I open 3 windows with the script running that should be okay right?

**Comment by jdholtz** [comment]
I’ll test sample passwords with special characters and get back to you on that. 

You only need to start the script for each reservation. So you’ll only need to start three separate ones if those people have different confirmation numbers.

**Comment by underqualifieditguy** [comment]
Oh okay, all 3 people are under the same confirmation number so I was thinking if I did one for each using the confirmation number method it would increase my odds of getting a better seating order.

**Comment by jdholtz** [comment]
I actually haven’t tried doing that before, so I’m not 100% sure but it should work. Please report it if it does not work as that would be an issue.

**Comment by underqualifieditguy** [comment]
Will do

**Comment by jdholtz** [comment]
I've been playing around with the special character thing a little. On any special character, you can put a `\` in front (assuming you are using bash) to pass the literal character into the script (If you aren't sure on the exact special characters that need it, you can also put a `\` in front of every character). Then, you should not need quotes.

> I only tried it twice, it failed on the very first attempt.

Did it work on the second attempt or fail twice?

**Comment by jdholtz** [comment]
Hey @underqualifieditguy, were you able to try my suggestions above yet?

**Comment by jdholtz** [comment]
Closing this due to inactivity. Please reopen this issue again if the problem still occurs after trying my suggestions.
