### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by harpreetchima** [jdholtz/auto-southwest-check-in#29]
I'm getting the follow error when trying to run the script:

Traceback (most recent call last):
  File "/root/auto-southwest-check-in/southwest.py", line 41, in <module>
    set_up(arguments)
  File "/root/auto-southwest-check-in/southwest.py", line 31, in set_up
    flight_retriever.checkin_scheduler.refresh_headers()
  File "/root/auto-southwest-check-in/lib/checkin_scheduler.py", line 81, in refresh_headers
    webdriver.set_headers()
  File "/root/auto-southwest-check-in/lib/webdriver.py", line 61, in set_headers
    driver = self._get_driver()
  File "/root/auto-southwest-check-in/lib/webdriver.py", line 44, in _get_driver
    driver = Chrome(options=self.options, seleniumwire_options=self.seleniumwire_options)
  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    browser = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1720, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

Everything was updated before I ran it. Thanks!

**Comment by jdholtz** [comment]
Hi. Do you get this error repeatedly if you run the script multiple times? I haven’t added any safety for when it fails to successfully connect to Southwest (which it does every once in a while).

**Comment by harpreetchima** [comment]
Yeah, I'm getting it on two machines (Windows/Ubuntu) and it's been about 5 hours between my first and most recent try. And I have tried two separate flights.

**Comment by jdholtz** [comment]
Thanks for checking on multiple machines. Unfortunately, I cannot reproduce this issue (I tried on two machines). Can you attempt to log in with the script and see if it works that way?

**Comment by jdholtz** [comment]
Hey @harpreetchima. I looked at the error a bit more and realized that it fails when trying to find Google Chrome. Do you have Google Chrome installed on your machine?

**Comment by jdholtz** [comment]
Closing this due to inactivity. Please reopen this issue again if the problem still occurs after verifying you have Google Chrome installed.

**Comment by harpreetchima** [comment]
> t the error a bit more and realized that it fails when trying to find Google Chrome. Do you have Google Chrome installed on your machine?

 Sorry for not replying before but that was indeed the issue! Works great now.
