### ISSUE TITLE
Crash when loading Southwest Homepage

### ISSUE THREAD

**Issue by spacezorro** [jdholtz/auto-southwest-check-in#312]
### Version

Auto-Southwest Check-In v8.0

### Browser Version

chrome=129.0.6668.100

### Description

when the southwest page is loading there is a southwest error popup #403050700 and the script crashes with

<div data-qa="placement-link">...</div> is not clickable at point (712, 836). Other element would receive the click: <div class="popup-head">...</div>

here is the after_page_load.png

https://imgur.com/tS85iZu

### To Reproduce

1. Run southwest.py -v 123456 password
2. Right after "DEBUG Process-1[webdriver:163]: Loading Southwest home page (this may take a moment)" it crashes

### Expected Behavior

Not to crash

### Relevant logs and program output

```sh
2024-10-18 16:05:44 DEBUG MainProcess[log:24]: Initialized the application
2024-10-18 16:05:44 DEBUG MainProcess[main:113]: Auto-Southwest Check-In v8.0
2024-10-18 16:05:44 DEBUG MainProcess[main:71]: Called with 2 arguments
2024-10-18 16:05:44 DEBUG MainProcess[config:143]: Initializing configuration file
2024-10-18 16:05:44 DEBUG MainProcess[config:172]: Reading the configuration file
2024-10-18 16:05:44 DEBUG MainProcess[config:176]: No configuration file found. Using defaults
2024-10-18 16:05:44 DEBUG MainProcess[config:185]: Reading configuration from environment variables
2024-10-18 16:05:44 DEBUG MainProcess[main:80]: Adding account through CLI arguments
2024-10-18 16:05:44 DEBUG MainProcess[config:155]: Creating configurations for 1 accounts
2024-10-18 16:05:44 INFO MainProcess[main:97]: Monitoring 1 account and 0 reservations

2024-10-18 16:05:44 DEBUG Process-1[reservation_monitor:68]: Acquiring lock...
2024-10-18 16:05:44 DEBUG Process-1[reservation_monitor:70]: Lock acquired
2024-10-18 16:05:44 DEBUG Process-1[reservation_monitor:209]: Retrieving reservations for account
2024-10-18 16:05:44 DEBUG Process-1[webdriver:135]: Starting webdriver for current session
2024-10-18 16:06:47 DEBUG Process-1[webdriver:157]: Using browser version: 129.0.6668.100
2024-10-18 16:06:47 DEBUG Process-1[webdriver:180]: Applying cached headers
2024-10-18 16:06:47 DEBUG Process-1[webdriver:163]: Loading Southwest home page (this may take a moment)
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/x/auto-southwest-check-in/lib/reservation_monitor.py", line 54, in monitor
    self._monitor()
  File "/home/x/auto-southwest-check-in/lib/reservation_monitor.py", line 72, in _monitor
    should_exit = self._check()
                  ^^^^^^^^^^^^^
  File "/home/x/auto-southwest-check-in/lib/reservation_monitor.py", line 190, in _check
    reservations, skip_scheduling = self._get_reservations()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/auto-southwest-check-in/lib/reservation_monitor.py", line 215, in _get_reservations
    reservations = webdriver.get_reservations(self)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/auto-southwest-check-in/lib/webdriver.py", line 106, in get_reservations
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/home/x/auto-southwest-check-in/lib/webdriver.py", line 166, in _get_driver
    driver.click("(//div[@data-qa='placement-link'])[2]")
  File "/home/x/auto-southwest-check-in/venv/lib/python3.12/site-packages/seleniumbase/core/sb_driver.py", line 58, in click
    page_actions.click(self.driver, *args, **kwargs)
  File "/home/x/auto-southwest-check-in/venv/lib/python3.12/site-packages/seleniumbase/fixtures/page_actions.py", line 1533, in click
    element.click()
  File "/home/x/auto-southwest-check-in/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/x/auto-southwest-check-in/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/x/auto-southwest-check-in/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/x/auto-southwest-check-in/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div data-qa="placement-link">...</div> is not clickable at point (712, 836). Other element would receive the click: <div class="popup-head">...</div>
  (Session info: chrome=129.0.6668.100)
Stacktrace:
#0 0x6407b90a4b9a <unknown>
#1 0x6407b8d8a670 <unknown>
#2 0x6407b8de08c6 <unknown>
#3 0x6407b8dde7e6 <unknown>
#4 0x6407b8ddc297 <unknown>
#5 0x6407b8ddb6a6 <unknown>
#6 0x6407b8dceae8 <unknown>
#7 0x6407b8dfeb82 <unknown>
#8 0x6407b8dce4c8 <unknown>
#9 0x6407b8dfed4e <unknown>
#10 0x6407b8e1ddd6 <unknown>
#11 0x6407b8dfe923 <unknown>
#12 0x6407b8dcc6e7 <unknown>
#13 0x6407b8dcd6de <unknown>
#14 0x6407b906e66b <unknown>
#15 0x6407b9072611 <unknown>
#16 0x6407b905a4e5 <unknown>
#17 0x6407b9073192 <unknown>
#18 0x6407b903f6ef <unknown>
#19 0x6407b90939d8 <unknown>
#20 0x6407b9093ba7 <unknown>
#21 0x6407b90a39ec <unknown>
#22 0x78df14e9ca94 <unknown>
#23 0x78df14f29c3c <unknown>
```

**Comment by dmytrokoren** [comment]
Use develop branch or
Docker: dmytrokoren/alpha-legacy-windock

**Comment by spacezorro** [comment]
@dmytrokoren 
jdholtz/develop gives the same error

Your docker image is a different error.
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div data-qa="placement-link">...</div> is not clickable at point (632, 696). Other element would receive the click: <div class="backdrop visible active"></div>

I am working on turning on the screenshots and extracting them from the image

Is your docker image built from? "modified_webdriver_and_updated_requirements"

**Comment by spacezorro** [comment]
meh it is the same error just different x,y coordinates

https://imgur.com/22MCc0w

**Comment by dmytrokoren** [comment]
@spacezorro - try this one, its build from 'modified_webdriver_and_updated_requirements'

dmytrokoren/auto-southwest-check-in:develop

**Comment by spacezorro** [comment]
So that logs in, but reservations are blocking..
I'm going to try for screenshots

`docker run --rm -it dmytrokoren/auto-southwest-check-in:develop -v $(cat venv/login)
2024-10-21 23:09:04 DEBUG MainProcess[log:24]: Initialized the application
2024-10-21 23:09:04 DEBUG MainProcess[main:115]: Auto-Southwest Check-In v8.0
2024-10-21 23:09:04 DEBUG MainProcess[main:73]: Called with 2 arguments
2024-10-21 23:09:04 DEBUG MainProcess[config:143]: Initializing configuration file
2024-10-21 23:09:04 DEBUG MainProcess[config:172]: Reading the configuration file
2024-10-21 23:09:04 DEBUG MainProcess[config:176]: No configuration file found. Using defaults
2024-10-21 23:09:04 DEBUG MainProcess[config:185]: Reading configuration from environment variables
2024-10-21 23:09:04 DEBUG MainProcess[main:82]: Adding account through CLI arguments
2024-10-21 23:09:04 DEBUG MainProcess[config:155]: Creating configurations for 1 accounts
2024-10-21 23:09:04 INFO MainProcess[main:99]: Monitoring 1 account and 0 reservations

2024-10-21 23:09:04 DEBUG Process-1[reservation_monitor:75]: Acquiring lock...
2024-10-21 23:09:04 DEBUG Process-1[reservation_monitor:77]: Lock acquired
2024-10-21 23:09:04 DEBUG Process-1[reservation_monitor:217]: Retrieving reservations for account
2024-10-21 23:09:05 DEBUG Process-1[webdriver:386]: Started virtual display successfully
2024-10-21 23:09:05 DEBUG Process-1[webdriver:157]: Starting webdriver for current session
2024-10-21 23:09:10 DEBUG Process-1[webdriver:170]: Using browser version: 119.0.6045.159
2024-10-21 23:09:10 DEBUG Process-1[webdriver:199]: Retrieving new headers
2024-10-21 23:09:10 DEBUG Process-1[webdriver:176]: Loading Southwest check-in page (this may take a moment)
2024-10-21 23:09:34 DEBUG Process-1[webdriver:112]: Logging into account to get a list of reservations and valid headers
2024-10-21 23:09:41 DEBUG Process-1[webdriver:240]: Waiting for 'headers_set' to be set (timeout: 90 seconds)
2024-10-21 23:09:41 DEBUG Process-1[webdriver:246]: 'headers_set' set successfully
2024-10-21 23:09:46 DEBUG Process-1[webdriver:232]: Login response has been received
2024-10-21 23:09:46 DEBUG Process-1[webdriver:236]: Upcoming trips response has been received
2024-10-21 23:09:49 DEBUG Process-1[webdriver:240]: Waiting for 'login_request_id' to be set (timeout: 90 seconds)
2024-10-21 23:09:49 DEBUG Process-1[webdriver:246]: 'login_request_id' set successfully
2024-10-21 23:09:49 DEBUG Process-1[webdriver:367]: First time logging in. Setting account name
Successfully logged in to Space Zorro's account

2024-10-21 23:09:49 DEBUG Process-1[webdriver:240]: Waiting for 'trips_request_id' to be set (timeout: 90 seconds)
2024-10-21 23:09:49 DEBUG Process-1[webdriver:246]: 'trips_request_id' set successfully
2024-10-21 23:09:50 DEBUG Process-1[webdriver:395]: Stopped virtual display successfully
2024-10-21 23:09:50 DEBUG Process-1[reservation_monitor:224]: Successfully retrieved 3 reservations after 1 attempts
2024-10-21 23:09:50 DEBUG Process-1[reservation_monitor:117]: Scheduling flight check-ins for 3 reservations
2024-10-21 23:09:50 DEBUG Process-1[checkin_scheduler:81]: Retrieving reservation information
2024-10-21 23:09:50 DEBUG Process-1[utils:90]: Request error on attempt 1: Forbidden (403). Sleeping for 2.38 seconds until next attempt
2024-10-21 23:09:53 DEBUG Process-1[utils:90]: Request error on attempt 2: Forbidden (403). Sleeping for 2.69 seconds until next attempt
2024-10-21 23:09:56 DEBUG Process-1[utils:90]: Request error on attempt 3: Forbidden (403). Sleeping for 1.25 seconds until next attempt
2024-10-21 23:09:57 DEBUG Process-1[utils:90]: Request error on attempt 4: Forbidden (403). Sleeping for 2.48 seconds until next attempt
2024-10-21 23:10:00 DEBUG Process-1[utils:90]: Request error on attempt 5: Forbidden (403). Sleeping for 1.51 seconds until next attempt
2024-10-21 23:10:02 DEBUG Process-1[utils:90]: Request error on attempt 6: Forbidden (403). Sleeping for 1.41 seconds until next attempt
2024-10-21 23:10:04 DEBUG Process-1[utils:90]: Request error on attempt 7: Forbidden (403). Sleeping for 2.01 seconds until next attempt
2024-10-21 23:10:06 DEBUG Process-1[utils:90]: Request error on attempt 8: Forbidden (403). Sleeping for 2.00 seconds until next attempt
`

**Comment by spacezorro** [comment]
none of the screenshots had value

**Comment by dmytrokoren** [comment]
@spacezorro try again with: dmytrokoren/auto-southwest-check-in:develop

as from previous issue headers_urls has been changes in this image and user_agent has been removed.

**Comment by spacezorro** [comment]
Sorry I missed this..

I have a international flight Saturday w/ a companion pass.

Repulled just a minute ago... I added the "-v" to the compose to make the log getting easier

It's logging in now, and seems to be mostly working.. Getting alot of 403/429's

Can probably close because the login problem is solved

**Comment by spacezorro** [comment]
There seems to be a problem with my international flight back (Process-2 near the 400310456) 

This is a weird error

> Error: Failed to retrieve reservation for -u southwest.py with confirmation number python3

```
2024-11-14 20:25:05 DEBUG Process-1[checkin_handler:53]: Scheduling check-in for current flight
2024-11-14 20:25:05 DEBUG Process-1[notification_handler:71]: Sending new flights notification
Successfully scheduled the following flights to check in for 

SNIP

International flights were scheduled. Make sure to fill out your passport information before the check-in date
2024-11-14 20:25:05 DEBUG Process-1:1[checkin_handler:101]: Sleeping until thirty minutes before check-in...
2024-11-14 20:25:05 DEBUG Process-1:2[checkin_handler:101]: Sleeping until thirty minutes before check-in...
2024-11-14 20:25:05 DEBUG Process-1:3[checkin_handler:101]: Sleeping until thirty minutes before check-in...
2024-11-14 20:25:05 DEBUG Process-1:4[checkin_handler:101]: Sleeping until thirty minutes before check-in...
2024-11-14 20:25:05 DEBUG Process-1:5[checkin_handler:101]: Sleeping until thirty minutes before check-in...
2024-11-14 20:25:05 DEBUG Process-1:6[checkin_handler:101]: Sleeping until thirty minutes before check-in...
2024-11-14 20:25:11 DEBUG Process-1[checkin_scheduler:143]: 6 flights are currently scheduled. Removing old flights
2024-11-14 20:25:11 DEBUG Process-1[checkin_scheduler:164]: Successfully removed old flights. 6 flights are now scheduled
2024-11-14 20:25:11 DEBUG Process-1[reservation_monitor:119]: Checking fares for 6 flights
2024-11-14 20:25:11 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2024-11-14 20:25:11 DEBUG Process-1[reservation_monitor:136]: Fare check is not supported with companion passes. Skipping are check
2024-11-14 20:25:11 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2024-11-14 20:25:11 DEBUG Process-1[reservation_monitor:136]: Fare check is not supported with companion passes. Skipping are check
2024-11-14 20:25:11 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2024-11-14 20:25:11 DEBUG Process-1[fare_checker:93]: Retrieving search information for the current flight
2024-11-14 20:25:15 DEBUG Process-1[utils:70]: Successfully made request after 1 attempts
2024-11-14 20:25:15 DEBUG Process-1[fare_checker:81]: Retrieving matching flights
2024-11-14 20:25:18 DEBUG Process-1[utils:70]: Successfully made request after 1 attempts
2024-11-14 20:25:18 DEBUG Process-1[fare_checker:47]: Found 26 matching flights
2024-11-14 20:25:18 DEBUG Process-1[fare_checker:34]: Flight price change found for +92 USD
2024-11-14 20:25:18 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2024-11-14 20:25:18 DEBUG Process-1[fare_checker:93]: Retrieving search information for the current flight
2024-11-14 20:25:19 DEBUG Process-1[utils:90]: Request error on attempt 1: Forbidden (403). Sleeping for 2.71 seconds until next attempt
2024-11-14 20:25:22 DEBUG Process-1[utils:90]: Request error on attempt 2: Forbidden (403). Sleeping for 2.24 seconds until next attempt
2024-11-14 20:25:24 DEBUG Process-1[utils:90]: Request error on attempt 3: Forbidden (403). Sleeping for 1.40 seconds until next attempt
2024-11-14 20:25:26 DEBUG Process-1[utils:90]: Request error on attempt 4: Forbidden (403). Sleeping for 1.10 seconds until next attempt
2024-11-14 20:25:27 DEBUG Process-1[utils:90]: Request error on attempt 5: Forbidden (403). Sleeping for 2.12 seconds until next attempt
2024-11-14 20:25:29 DEBUG Process-1[utils:90]: Request error on attempt 6: Forbidden (403). Sleeping for 1.24 seconds until next attempt
2024-11-14 20:25:31 DEBUG Process-1[utils:90]: Request error on attempt 7: Forbidden (403). Sleeping for 2.32 seconds until next attempt
2024-11-14 20:25:33 DEBUG Process-1[utils:96]: Failed to make request after 7 attempts: Forbidden (403)
2024-11-14 20:25:33 DEBUG Process-1[utils:97]: Response body: {
  "code": 403050700
}
2024-11-14 20:25:33 ERROR Process-1[reservation_monitor:131]: Requesting error during fare check. Forbidden (403). Skipping...
2024-11-14 20:25:33 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2024-11-14 20:25:33 DEBUG Process-1[fare_checker:93]: Retrieving search information for the current flight
2024-11-14 20:25:33 DEBUG Process-1[utils:90]: Request error on attempt 1: Forbidden (403). Sleeping for 1.23 seconds until next attempt
2024-11-14 20:25:36 DEBUG Process-1[utils:70]: Successfully made request after 2 attempts
2024-11-14 20:25:36 DEBUG Process-1[fare_checker:81]: Retrieving matching flights
2024-11-14 20:25:37 DEBUG Process-1[utils:90]: Request error on attempt 1: Too Many Requests (429). Sleeping for 1.69 seconds until next attempt
2024-11-14 20:25:38 DEBUG Process-1[utils:90]: Request error on attempt 2: Too Many Requests (429). Sleeping for 2.44 seconds until next attempt
2024-11-14 20:25:41 DEBUG Process-1[utils:90]: Request error on attempt 3: Too Many Requests (429). Sleeping for 1.08 seconds until next attempt
2024-11-14 20:25:45 DEBUG Process-1[utils:70]: Successfully made request after 4 attempts
2024-11-14 20:25:45 DEBUG Process-1[fare_checker:47]: Found 26 matching flights
2024-11-14 20:25:45 DEBUG Process-1[fare_checker:34]: Flight price change found for +83 USD
2024-11-14 20:25:45 DEBUG Process-1[fare_checker:30]: Checking current price for flight
2024-11-14 20:25:45 DEBUG Process-1[fare_checker:93]: Retrieving search information for the current flight
2024-11-14 20:25:45 DEBUG Process-1[utils:90]: Request error on attempt 1: Forbidden (403). Sleeping for 1.45 seconds until next attempt
2024-11-14 20:25:49 DEBUG Process-1[utils:70]: Successfully made request after 2 attempts
2024-11-14 20:25:49 DEBUG Process-1[fare_checker:81]: Retrieving matching flights
2024-11-14 20:25:49 DEBUG Process-1[utils:90]: Request error on attempt 1: Too Many Requests (429). Sleeping for 1.16 seconds until next attempt
2024-11-14 20:25:51 DEBUG Process-1[utils:90]: Request error on attempt 2: Too Many Requests (429). Sleeping for 1.41 seconds until next attempt
2024-11-14 20:25:55 DEBUG Process-1[utils:70]: Successfully made request after 3 attempts
2024-11-14 20:25:55 DEBUG Process-1[fare_checker:47]: Found 26 matching flights
2024-11-14 20:25:55 DEBUG Process-1[fare_checker:34]: Flight price change found for +193 USD
2024-11-14 20:25:55 DEBUG Process-1[reservation_monitor:81]: Lock released
2024-11-14 20:25:55 DEBUG Process-2[reservation_monitor:70]: Lock acquired
2024-11-14 20:25:55 DEBUG Process-2[checkin_scheduler:48]: Refreshing headers for current session
2024-11-14 20:25:55 DEBUG Process-2[webdriver:131]: Starting webdriver for current session
2024-11-14 20:25:56 DEBUG Process-2[webdriver:295]: Started virtual display successfully
2024-11-14 20:25:56 DEBUG Process-1[reservation_monitor:154]: Sleeping for 86289 seconds
2024-11-14 20:25:58 DEBUG Process-2[webdriver:154]: Using browser version: 119.0.6045.159
2024-11-14 20:25:58 DEBUG Process-2[webdriver:158]: Loading Southwest home page (this may take a moment)
2024-11-14 20:26:09 DEBUG Process-2[webdriver:89]: Waiting for valid headers
2024-11-14 20:26:09 DEBUG Process-2[webdriver:188]: Waiting for headers_set to be set (timeout: 180 seconds)
2024-11-14 20:26:11 DEBUG Process-2[webdriver:202]: headers_set set successfully
2024-11-14 20:26:11 DEBUG Process-2[webdriver:304]: Stopped virtual display successfully
2024-11-14 20:26:11 DEBUG Process-2[reservation_monitor:110]: Scheduling flight check-ins for 1 reservations
2024-11-14 20:26:11 DEBUG Process-2[checkin_scheduler:81]: Retrieving reservation information
2024-11-14 20:26:11 DEBUG Process-2[utils:90]: Request error on attempt 1: Forbidden (403). Sleeping for 1.54 seconds until next attempt
2024-11-14 20:26:13 DEBUG Process-2[utils:90]: Request error on attempt 2: Forbidden (403). Sleeping for 1.94 seconds until next attempt
2024-11-14 20:26:15 DEBUG Process-2[utils:90]: Request error on attempt 3: Forbidden (403). Sleeping for 2.67 seconds until next attempt
2024-11-14 20:26:18 DEBUG Process-2[utils:96]: Failed to make request after 4 attempts: Bad Request (400)
2024-11-14 20:26:18 DEBUG Process-2[utils:97]: Response body: {"code":400310456,"message":"Record Locator must have six characters","messageKey":"VALIDATION__AIR_RESERVATION__RECORD_LOCATOR__LENGTH","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"no-exp-id:0.3eed0117.1731615978.45f2a127:mweb","infoList":[{"key":"recordLocator","value":"Record Locator must have six characters"}]}
2024-11-14 20:26:18 DEBUG Process-2[checkin_scheduler:87]: Failed to retrieve reservation info. Error: Invalid confirmation number length. Exiting
2024-11-14 20:26:18 DEBUG Process-2[notification_handler:80]: Sending failed reservation retrieval notification...
Error: Failed to retrieve reservation for -u southwest.py with confirmation number python3. Reason: Invalid confirmation number length.
Make sure the reservation information is correct and try again.
2024-11-14 20:26:24 DEBUG Process-2[checkin_scheduler:56]: 0 flights found under current reservation
2024-11-14 20:26:24 DEBUG Process-2[checkin_scheduler:44]: 0 total flights were found
2024-11-14 20:26:24 DEBUG Process-2[checkin_scheduler:111]: Updating scheduled flights (0 scheduled, 0 found)
2024-11-14 20:26:24 DEBUG Process-2[checkin_scheduler:125]: 0 new flights found
2024-11-14 20:26:24 DEBUG Process-2[checkin_scheduler:131]: Scheduling 0 flights for check-in
2024-11-14 20:26:24 DEBUG Process-2[checkin_scheduler:143]: 0 flights are currently scheduled. Removing old flights
2024-11-14 20:26:24 DEBUG Process-2[checkin_scheduler:164]: Successfully removed old flights. 0 flights are now scheduled
2024-11-14 20:26:24 DEBUG Process-2[reservation_monitor:103]: No more flights are scheduled for check-in. Exiting...
2024-11-14 20:26:24 DEBUG Process-2[reservation_monitor:74]: Stopping monitoring
```

It did the same thing for my companion
```
2024-11-14 20:24:57 DEBUG Process-1[checkin_scheduler:94]: Successfully retrieved reservation information
2024-11-14 20:24:57 DEBUG Process-1[checkin_scheduler:56]: 2 flights found under current reservation
2024-11-14 20:24:57 DEBUG Process-1[checkin_scheduler:44]: 2 total flights were found
2024-11-14 20:24:57 DEBUG Process-1[checkin_scheduler:111]: Updating scheduled flights (0 scheduled, 2 found)
2024-11-14 20:24:57 DEBUG Process-1[checkin_scheduler:125]: 2 new flights found
2024-11-14 20:24:57 DEBUG Process-1[checkin_scheduler:131]: Scheduling 2 flights for check-in
2024-11-14 20:24:57 DEBUG Process-1[checkin_handler:53]: Scheduling check-in for current flight
2024-11-14 20:24:57 DEBUG Process-1[checkin_handler:53]: Scheduling check-in for current flight

SNIP

2024-11-14 20:25:03 DEBUG Process-1[reservation_monitor:154]: Sleeping for 86347 seconds

SNIP

2024-11-14 20:25:19 DEBUG Process-2[reservation_monitor:110]: Scheduling flight check-ins for 1 reservations
2024-11-14 20:25:19 DEBUG Process-2[checkin_scheduler:81]: Retrieving reservation information
2024-11-14 20:25:19 DEBUG Process-2[utils:90]: Request error on attempt 1: Forbidden (403). Sleeping for 1.31 seconds until next attempt
2024-11-14 20:25:21 DEBUG Process-2[utils:90]: Request error on attempt 2: Forbidden (403). Sleeping for 2.86 seconds until next attempt
2024-11-14 20:25:24 DEBUG Process-2[utils:90]: Request error on attempt 3: Forbidden (403). Sleeping for 1.70 seconds until next attempt
2024-11-14 20:25:26 DEBUG Process-2[utils:90]: Request error on attempt 4: Forbidden (403). Sleeping for 1.48 seconds until next attempt
2024-11-14 20:25:27 DEBUG Process-2[utils:90]: Request error on attempt 5: Forbidden (403). Sleeping for 1.62 seconds until next attempt
2024-11-14 20:25:29 DEBUG Process-2[utils:90]: Request error on attempt 6: Forbidden (403). Sleeping for 2.44 seconds until next attempt
2024-11-14 20:25:32 DEBUG Process-2[utils:90]: Request error on attempt 7: Forbidden (403). Sleeping for 1.37 seconds until next attempt
2024-11-14 20:25:33 DEBUG Process-2[utils:90]: Request error on attempt 8: Forbidden (403). Sleeping for 2.35 seconds until next attempt
2024-11-14 20:25:36 DEBUG Process-2[utils:96]: Failed to make request after 9 attempts: Bad Request (400)
2024-11-14 20:25:36 DEBUG Process-2[utils:97]: Response body: {"code":400310456,"message":"Record Locator must have six characters","messageKey":"VALIDATION__AIR_RESERVATION__RECORD_LOCATOR__LENGTH","header":null,"httpStatusCode":"BAD_REQUEST","requestId":"no-exp-id:0.3ced0117.1731615936.1be7122b:mweb","infoList":[{"key":"recordLocator","value":"Record Locator must have six characters"}]}
2024-11-14 20:25:36 DEBUG Process-2[checkin_scheduler:87]: Failed to retrieve reservation info. Error: Invalid confirmation number length. Exiting
2024-11-14 20:25:36 DEBUG Process-2[notification_handler:80]: Sending failed reservation retrieval notification...
Error: Failed to retrieve reservation for -u southwest.py with confirmation number python3. Reason: Invalid confirmation number length.
Make sure the reservation information is correct and try again.
2024-11-14 20:25:41 DEBUG Process-2[checkin_scheduler:56]: 0 flights found under current reservation
2024-11-14 20:25:41 DEBUG Process-2[checkin_scheduler:44]: 0 total flights were found
2024-11-14 20:25:41 DEBUG Process-2[checkin_scheduler:111]: Updating scheduled flights (0 scheduled, 0 found)
2024-11-14 20:25:41 DEBUG Process-2[checkin_scheduler:125]: 0 new flights found
2024-11-14 20:25:41 DEBUG Process-2[checkin_scheduler:131]: Scheduling 0 flights for check-in
2024-11-14 20:25:41 DEBUG Process-2[checkin_scheduler:143]: 0 flights are currently scheduled. Removing old flights
2024-11-14 20:25:41 DEBUG Process-2[checkin_scheduler:164]: Successfully removed old flights. 0 flights are now scheduled
2024-11-14 20:25:41 DEBUG Process-2[reservation_monitor:103]: No more flights are scheduled for check-in. Exiting...
2024-11-14 20:25:41 DEBUG Process-2[reservation_monitor:74]: Stopping monitoring
```

**Comment by jdholtz** [comment]
> This is a weird error
> >   Error: Failed to retrieve reservation for -u southwest.py with confirmation number python3

Could you send the beginning of these logs too? It looks like you may be invoking the script incorrectly. Is this dmytrokoren's image or the develop branch for this repository?

**Comment by dmytrokoren** [comment]
dmytrokoren/auto-southwest-check-in:develop

This is updated with latest develop branch

**Comment by dmytrokoren** [comment]
@spacezorro can you provide your config.json file and what is the command you using to trigger the script?

**Comment by spacezorro** [comment]
I am using dmytrokoren/auto-southwest-check-in:develop as of ~11am

southwest.yml
```
version: "3.0"

services:

  southwest-spacezorro:
    image: dmytrokoren/auto-southwest-check-in:develop
    depends_on:
      - signal
    volumes:
      - /var/data/config/southwest/spacezorro.json:/app/config.json
    command: ["python3", "-u", "southwest.py", "-v"]

  southwest-companion:
    image: dmytrokoren/auto-southwest-check-in:develop
    depends_on:
      - signal
    volumes:
      - /var/data/config/southwest/companion.json:/app/config.json
    command: ["python3", "-u", "southwest.py", "-v"]

  signal:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=normal
    volumes:
      - /var/data/config/southwest/signal-cli-config:/home/.local/share/signal-cli
```

spacezorro.json (companion is the same except for user/pass and notification address/phone)
```
{
  "check_fares": "same_day",
  "notification_level": 1,
  "retrieval_interval": 24,
  "notification_urls": [
    "mailtos://user:pass@gmail.com?from=SW-Checkin<sz@gmail.com>&to=sz@gmail.com",
    "signal://signal.local.lan/18885551212/18885551212"
  ],
  "accounts": [
    {
      "username": "123456789",
      "password": "SooperSekrit",
      "notification_level": 2,
      "notification_urls": [
        "mailtos://user:pass@gmail.com?from=SW-User-Checkin<sz@gmail.com>&to=enduser@gmail.com",
        "signal://signal.local.lan/18885551212/18885551234"
      ]
    }
  ]
}
```

**Comment by spacezorro** [comment]
So the checkin worked.

There is something weird about my international leg. Even though I put all my passport info in the system won't let me check in to the international unless i redo my passport num/exp.

**Comment by spacezorro** [comment]
So i am flying back on the 24th and am running shepherd, so if you want to push another develop image it will automagically update and we will see what happens.

**Comment by dmytrokoren** [comment]
> So i am flying back on the 24th and am running shepherd, so if you want to push another develop image it will automagically update and we will see what happens.

Thanks for update. What image needs to be pushed?

**Comment by spacezorro** [comment]
Not sure.. You can probably close this because the root issue is resolved.

> Failed to retrieve reservation for -u southwest.py with confirmation number python3.

It looks like it's trying to check in with the username "-u" "southwest.py" and the confirmation "python3"

**Comment by jdholtz** [comment]
> Not sure.. You can probably close this because the root issue is resolved.

Thanks for verifying @spacezorro. The new changes from dmytrokoren's branch have been merged so the homepage won't even load anymore (it'll be the check-in page instead, and the click function--which threw the exception--was removed).

> It looks like it's trying to check in with the username "-u" "southwest.py" and the confirmation "python3"

The container already runs the script with `python3 -u southwest.py`. The `command:` attribute in Docker Compose adds arguments onto this command, so you are technically running `python3 -u southwest.py python3 -u southwest.py -v`. All you need to do is change the this part in your docker-compose.yml `command: ["-v"]`.
