### ISSUE TITLE
Ran Script, nothing happened

### ISSUE THREAD

**Issue by edshaw42** [jdholtz/auto-southwest-check-in#37]
Installed locally on my mac, when I passed it the info my terminal just sat. Ended up checking in manually on my phone. I most likely did something wrong, but is there a good way to test this for future use cases?

**Comment by jdholtz** [comment]
That’s strange. How long did you let it sit? Sometimes the browser can take a while to navigate the web page. If the check-in was less than 24 hours ago, you should be able to check in with the script again as Southwest wouldn’t have closed it yet.

**Comment by edshaw42** [comment]
I left it for about 30 seconds and then manually checked in.. Will it give some sort of error if already checked in? Trying to see how best to test?

**Comment by edshaw42** [comment]
Is there a way to log what it's doing? Trying again, and nothing is happening. I am already manually checked into the flight.

It seems like it's doing things, but can't get any clarity?

**Comment by edshaw42** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/85707702/216794726-37deb258-4f3e-4151-bdde-2edb6b7d3c2e.png">

**Comment by edshaw42** [comment]
Just sits here

**Comment by jdholtz** [comment]
It will still work fine even if you are already checked in to your flight. Unfortunately, there are no logs yet. What version of Google Chrome are you running? It seems to most likely be an issue with the web browser. 

If you want to debug it more, you’ll have to add your own code in the script (I have plans to add a logger soon). You can put `print("debug")` between lines 46 and 47 in `lib/webdriver.py` and re-execute the script to see if it prints anything out. If it doesn’t, it’s an issue with the browser.

**Comment by edshaw42** [comment]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/85707702/216800836-7117e98d-08b1-4612-a604-42f8669ef64a.png">
![Uploading image.png…]()

**Comment by edshaw42** [comment]
python3 downloads/auto-southwest-check-in-master/southwest.py <redacted>
Traceback (most recent call last):
  File "/Users/<redacted>/downloads/auto-southwest-check-in-master/southwest.py", line 41, in <module>
    set_up(arguments)
  File "/Users/<redacted>/downloads/auto-southwest-check-in-master/southwest.py", line 31, in set_up
    flight_retriever.checkin_scheduler.refresh_headers()
  File "/Users/<redacted>/Downloads/auto-southwest-check-in-master/lib/checkin_scheduler.py", line 81, in refresh_headers
    webdriver.set_headers()
  File "/Users/<redacted>/Downloads/auto-southwest-check-in-master/lib/webdriver.py", line 62, in set_headers
    driver = self._get_driver()
  File "/Users/<redacted>/Downloads/auto-southwest-check-in-master/lib/webdriver.py", line 44, in _get_driver
    driver = Chrome(options=self.options, seleniumwire_options=self.seleniumwire_options)
  File "/opt/homebrew/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 242, in __init__
    patcher.auto()
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 130, in auto
    self.unzip_package(self.fetch_package())
  File "/opt/homebrew/lib/python3.10/site-packages/undetected_chromedriver/patcher.py", line 166, in fetch_package
    return urlretrieve(u)[0]
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1352, in do_open
    r = h.getresponse()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by jdholtz** [comment]
It could potentially be because the undetected_chromedriver package is downloading a different architecture for ChromeDriver (rather than ARM). I can add a configuration option to provide a path to a custom ChromeDriver. Then, you can download a version that works for you and use that instead.

**Comment by edshaw42** [comment]
Installed on home server, and getting this now, it is a windows machine. Chrome is updated. 
 
 File "C:\auto-southwest-check-in-master\southwest.py", line 8, in <module>
    from lib.flight_retriever import AccountFlightRetriever, FlightRetriever
  File "C:\auto-southwest-check-in-master\lib\flight_retriever.py", line 5, in <module>
    from .checkin_scheduler import CheckInScheduler
  File "C:\auto-southwest-check-in-master\lib\checkin_scheduler.py", line 9, in <module>
    from .webdriver import WebDriver
  File "C:\auto-southwest-check-in-master\lib\webdriver.py", line 8, in <module>
    from selenium.webdriver.common.by import By
ModuleNotFoundError: No module named 'selenium'

**Comment by edshaw42** [comment]
ImportError: DLL load failed while importing _brotli: The specified module could not be found.

Tried installing on a windows server I have to see if that was my issue, getting this now.. Ideas?

**Comment by schmeed** [comment]
> ImportError: DLL load failed while importing _brotli: The specified module could not be found.
> 
> Tried installing on a windows server I have to see if that was my issue, getting this now.. Ideas?

Got the same error and the fix was to install Visual C++ redistributable.
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by jdholtz** [comment]
I found the same fix [here](https://github.com/google/brotli/issues/782#issuecomment-559516099). Thanks for sharing that @schmeed.

**Comment by edshaw42** [comment]
Awesome, that got me a step further haha. Now getting undetected chrome driver, but I think that's been talked about

**Comment by edshaw42** [comment]
> Awesome, that got me a step further haha. Now getting undetected chrome driver, but I think that's been talked about

 
![image](https://user-images.githubusercontent.com/85707702/217662688-2f66e570-1579-4778-b005-734edf88fb83.png)

**Comment by jdholtz** [comment]
There is more details about this issue [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/955). Could you try updating Google Chrome to the latest version? Should be `110.0.5481.77`.

**Comment by edshaw42** [comment]
It's actually on 110.0.5481.78
@jdholtz

**Comment by edshaw42** [comment]
@jdholtz - downloaded the most recent ChromeDriver but chrome is at .78 now.. Could the mismatch be the issue? Getting the same error in connection to chrome.

**Comment by jdholtz** [comment]
What is your version of ChromeDriver? They need to be the same version (undetected chromedriver should've handled downloading the latest version for you).

**Comment by edshaw42** [comment]
@jdholtz - so I just used a reservation from earlier in the week that's expired just to see if I could test it. 
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/85707702/217690298-edda9bbb-c8e8-4eea-bd8a-9f041724b3f6.png">
Do we think this means it would have worked?

**Comment by jdholtz** [comment]
Yes, it should output that as the reservation is no longer valid. The error at the end can be ignored as it didn't affect the script until it was finished. Could you try using your account information in the script? That will give us a much clearer idea of whether it worked or not. It should say "Successfully logged into ...'s account".

**Comment by edshaw42** [comment]
@jdholtz 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/85707702/217692788-2e4a2fbb-579c-4baa-b4c1-c7b1921e0f19.png">

**Comment by jdholtz** [comment]
This means it failed to log in. I catch this error in the `develop` branch, so hopefully in the future it will be more informative.

Anyways, there are actually issues with version 110 of Google Chrome currently (see #39). I have a fix on the [chrome_configuration](https://github.com/jdholtz/auto-southwest-check-in/tree/chrome_configuration) branch. Can you try downgrading Google Chrome to version 109 and downloading Chromedriver 109 from [here](https://chromedriver.chromium.org/downloads)? Make sure to specify the `chromedriver_path` in the `config.json` (you can see the details in the Configuration Doc).

To get those changes, run `git pull && git checkout chrome_configuration`

**Comment by jdholtz** [comment]
It would also be great if you could try downloading the chromedriver version that goes with your mac (make sure to select the right architecture too) and specifying its path in the `config.json`. This could potentially be the issue you are facing on there.

**Comment by jdholtz** [comment]
No worries. What issue are you running into? The same one? I highly advise you use git for versioning (using my command above) rather than manually downloading it.

**Comment by edshaw42** [comment]
Same errors about chrome driver errors. I want this to work so bad….!

**Comment by jdholtz** [comment]
What Python version are you currently on?

**Comment by edshaw42** [comment]
@jdholtz - 3.10.8 on mac, I think 3.11 on server. 

Do you have some good step by step for docker, I am pretty new to all of this.

**Comment by jdholtz** [comment]
The Readme should have all the steps you need to do. Just make sure you have docker installed before.

**Comment by edshaw42** [comment]
@jdholtz 

Followed the instructions as you said in read me for docker, getting this: 


Traceback (most recent call last):
  File "/app/southwest.py", line 41, in <module>
    set_up(arguments)
  File "/app/southwest.py", line 24, in set_up
    flight_retriever.monitor_account()
  File "/app/lib/flight_retriever.py", line 53, in monitor_account
    flights = self._get_flights()
  File "/app/lib/flight_retriever.py", line 65, in _get_flights
    flights = webdriver.get_flights(self)
  File "/app/lib/webdriver.py", line 90, in get_flights
    driver = self._get_driver()
  File "/app/lib/webdriver.py", line 44, in _get_driver
    driver = Chrome(options=self.options, seleniumwire_options=self.seleniumwire_options)
  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:33981
from unknown error: unable to discover open pages
Stacktrace:
#0 0x55de029ced93 <unknown>
#1 0x55de0279d2d7 <unknown>
#2 0x55de027ca2f4 <unknown>
#3 0x55de027c12fc <unknown>
#4 0x55de028064f4 <unknown>
#5 0x55de027fd353 <unknown>
#6 0x55de027cce40 <unknown>
#7 0x55de027ce038 <unknown>
#8 0x55de02a228be <unknown>
#9 0x55de02a268f0 <unknown>
#10 0x55de02a06f90 <unknown>
#11 0x55de02a27b7d <unknown>
#12 0x55de029f8578 <unknown>
#13 0x55de02a4c348 <unknown>
#14 0x55de02a4c4d6 <unknown>
#15 0x55de02a66341 <unknown>
#16 0x7f2cc54f8402 <unknown>

**Comment by jdholtz** [comment]
This is the same error that is currently happening with Chrome 110. You can follow #39 for more information on this, but currently there isn’t a fix.

**Comment by edshaw42** [comment]
@jdholtz - Installed Develop and was able to get logged in this time!!! 

When is says it "scheduled" check in, what does it do exactly? Does power off of the server cause it to lose that schedule?

Also - with experience do what kind of boarding group number have you all gotten??

**Comment by jdholtz** [comment]
Great to hear!

> When is says it "scheduled" check in, what does it do exactly? Does power off of the server cause it to lose that schedule?

It will sleep until five seconds before the check-in. Then it will start trying to check-in until it either runs out of attempts or succeeds. If you power off your server, you will have to restart the script for it to re-schedule the check-in

>  Also - with experience do what kind of boarding group number have you all gotten??

I usually get A45 to B15, although it definitely depends on how many people have prepaid and how fast your network connection is.

Were you able to get it to work on your Mac? I'm doubtful whether it will work on ARM architecture right now.

**Comment by edshaw42** [comment]
@jdholtz - Awesome thanks for the insight, I got the apprise notifications working as well, awesome job on this man! 


The mac is the next test, since it's up and running on the server. I will keep you updated.
