### ISSUE TITLE
SSL Cert Error

### ISSUE THREAD

**Issue by toddhsimmons** [jdholtz/auto-southwest-check-in#72]
### Description

I'm pretty sure I'm doing something wrong as I'm not sure where I should be setting the home browser info.  The error I keep getting though is:

urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

<details>
<summary>config.json</summary>

{
    "notification_urls": "",
    "notification_level": 1,
    "retrieval_interval": 24,
    "accounts": [
        {
            "username": "todd",
            "password": "password"
        }
    ],
    "flights": []
}

</details>

### To Reproduce

Running the file creates the error everytime.  

### Version

Auto-Southwest Check-In v3.1

### Additional context

Here is the output from --verbose:

<details>
<summary>Output</summary>

tsimmon8@UTO-D6JWVF12VJ auto-southwest-check-in % python3 southwest.py --verbose
2023-04-14 21:00:46 DEBUG MainProcess[log]: Initialized the application
2023-04-14 21:00:46 DEBUG MainProcess[main]: Called with 0 arguments
2023-04-14 21:00:46 DEBUG MainProcess[config]: Reading the configuration file
2023-04-14 21:00:46 DEBUG MainProcess[config]: Adding 1 accounts from configuration file
2023-04-14 21:00:46 DEBUG MainProcess[config]: Adding 0 flights from configuration file
2023-04-14 21:00:46 DEBUG MainProcess[config]: Setting notification level to 1
2023-04-14 21:00:46 DEBUG MainProcess[config]: Using 1 notification services
2023-04-14 21:00:46 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-04-14 21:00:46 DEBUG MainProcess[main]: Monitoring 1 accounts and 0 flights
2023-04-14 21:00:47 DEBUG Process-1[flight_retriever]: Retrieving flights for account
2023-04-14 21:00:47 DEBUG Process-1[webdriver]: Starting webdriver for current session
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/flight_retriever.py", line 64, in monitor_account
    flights = self._get_flights()
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/flight_retriever.py", line 85, in _get_flights
    flights = webdriver.get_flights(self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/webdriver.py", line 90, in get_flights
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/webdriver.py", line 140, in _get_driver
    driver = Chrome(
             ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 242, in __init__
    patcher.auto()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 127, in auto
    release = self.fetch_release_number()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

</details>

**Comment by toddhsimmons** [comment]
I was able to get chromedriver installed and validated it is working.  I have chromedriver in /usr/local/bin with the updated config.json

{
    "notification_urls": "",
    "notification_level": 1,
    "retrieval_interval": 24,
    "accounts": [
        {
            "username": "todd",
            "password": "password"
        }
    ],
    "chrome_version": 112,
    "chromedriver_path": "/usr/local/bin/chromedriver",
    "flights": []
}

tsimmon8@UTO-D6JWVF12VJ auto-southwest-check-in % python3 southwest.py --verbose
2023-04-14 22:21:01 DEBUG MainProcess[log]: Initialized the application
2023-04-14 22:21:01 DEBUG MainProcess[main]: Called with 0 arguments
2023-04-14 22:21:01 DEBUG MainProcess[config]: Reading the configuration file
2023-04-14 22:21:01 DEBUG MainProcess[config]: Adding 1 accounts from configuration file
2023-04-14 22:21:01 DEBUG MainProcess[config]: Setting chrome version to 112
2023-04-14 22:21:01 DEBUG MainProcess[config]: Setting custom Chromedriver path
2023-04-14 22:21:01 DEBUG MainProcess[config]: Adding 0 flights from configuration file
2023-04-14 22:21:01 DEBUG MainProcess[config]: Setting notification level to 1
2023-04-14 22:21:01 DEBUG MainProcess[config]: Using 1 notification services
2023-04-14 22:21:01 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-04-14 22:21:01 DEBUG MainProcess[main]: Monitoring 1 accounts and 0 flights
2023-04-14 22:21:02 DEBUG Process-1[flight_retriever]: Retrieving flights for account
2023-04-14 22:21:02 DEBUG Process-1[webdriver]: Starting webdriver for current session
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/flight_retriever.py", line 64, in monitor_account
    flights = self._get_flights()
              ^^^^^^^^^^^^^^^^^^^
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/flight_retriever.py", line 85, in _get_flights
    flights = webdriver.get_flights(self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/webdriver.py", line 90, in get_flights
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/tsimmon8/Automation Projects/Southwest Checkin/auto-southwest-check-in/lib/webdriver.py", line 140, in _get_driver
    driver = Chrome(
             ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 101, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 104, in start
    self.assert_process_still_running()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    raise WebDriverException(f"Service {self.path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/bin/chromedriver unexpectedly exited. Status code was: -9

**Comment by jdholtz** [comment]
Hi. What version of `certifi` do you have? You can find that out by running `pip show certifi`. You can try upgrading that to the latest version to see if that fixes the certificate issue (`pip install --upgrade certifi`).

I’m not sure why the second error is happening, but it might be because of the SSL error too.

**Comment by jdholtz** [comment]
Hi. What version of `certifi` do you have? You can find that out by running `pip show certifi`. You can try upgrading that to the latest version to see if that fixes the certificate issue (`pip install --upgrade certifi`).

I’m not sure why the second error is happening, but it might be because of the SSL error too.

**Comment by jdholtz** [comment]
Hey @toddhsimmons. Have you been able to try my suggestions above yet?

**Comment by jdholtz** [comment]
Closing this due to inactivity. Please reopen this issue again if the problem still occurs after trying my suggestions.
