### ISSUE TITLE
Error setting name of account on first login

### ISSUE THREAD

**Issue by fusionneo** [jdholtz/auto-southwest-check-in#74]
### Description

When attempting to log into a Southwest account for the first time, the application crashes.  It happens regardless of whether account is loaded from config.json or by setting a username/password in command line.

### To Reproduce

1. Run the script using an account that has not logged in before.
2. Wait for the crash.

### Version

Auto-Southwest Check-In v3.1

### Additional context

I am using the fare_checker branch. I have added a bit of additional code to try and debug the issue myself. I have changed the Chromedriver instance to be visible and I can confirm it is successfully logging in. I am also logging the response that is causing the script to crash. 

```
        response = driver.requests[0].response
        print(driver.requests[0])
        print(driver.requests[0].response)
        print(driver.requests[0].response.body)
        if response.status_code != 200:
            error = self._handle_login_error(response)
            raise error

        # If this is the first time logging in, the account name needs to be set
        # because that info is needed later
        if flight_retriever.first_name is None:
            logger.debug("First time logging in. Setting account name")
            response_body = json.loads(response.body)
            self._set_account_name(flight_retriever, response_body)
           ### THIS IS WHERE THE CRASH OCCURS ^^^^
            print(
                f"Successfully logged in to {flight_retriever.first_name} "
                f"{flight_retriever.last_name}'s account\n"
            )  # Don't log as it contains sensitive information
```

The print statements are my own additions and the output of the statements is the following:

```
https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
200
b'["gaia.l.a.r",[]]'
```

Here is the traceback information:

```
Traceback (most recent call last):
  File "C:\Users\fusio\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\fusio\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\fusio\OneDrive\Desktop\Personal Projects\Southwest\auto-southwest-check-in\lib\flight_retriever.py", line 115, in monitor_account
    flights = self._get_flights()
  File "C:\Users\fusio\OneDrive\Desktop\Personal Projects\Southwest\auto-southwest-check-in\lib\flight_retriever.py", line 131, in _get_flights
[auto-southwest-check-in.log](https://github.com/jdholtz/auto-southwest-check-in/files/11246109/auto-southwest-check-in.log)

    flights = webdriver.get_flights(self)
  File "C:\Users\fusio\OneDrive\Desktop\Personal Projects\Southwest\auto-southwest-check-in\lib\webdriver.py", line 128, in get_flights
    self._set_account_name(flight_retriever, response_body)
  File "C:\Users\fusio\OneDrive\Desktop\Personal Projects\Southwest\auto-southwest-check-in\lib\webdriver.py", line 202, in _set_account_name
    flight_retriever.first_name = response["customers.userInformation.firstName"]
TypeError: list indices must be integers or slices, not str

```

The most recent log has been attached.

**Comment by fusionneo** [comment]
Okay, I fixed this. The weird Google requests that were in there were causing the script to parse the wrong request for account name.

```
def get_flights(self, flight_retriever: AccountFlightRetriever) -> Dict[str, Any]:
        """
        Logs into the flight retriever account to retrieve a list of scheduled flights.
        Since valid headers are produced, they are also grabbed and updated in the check-in
        scheduler. Last, if the account name is not set, it will set it based on the response
        information.
        """
        driver = self._get_driver()
        logger.debug("Logging into Southwest account to get scheduled flights and valid headers")

        # Log in to retrieve the account's trips and needed headers for later requests
        WebDriverWait(driver, 30).until(EC.invisibility_of_element((By.CLASS_NAME, "dimmer")))
        WebDriverWait(driver, 30).until(
            EC.element_to_be_clickable((By.CLASS_NAME, "login-button--box"))
        ).click()

        username_element = WebDriverWait(driver, 30).until(
            EC.presence_of_element_located((By.NAME, "userNameOrAccountNumber"))
        )
        username_element.send_keys(flight_retriever.username)

        password_element = WebDriverWait(driver, 30).until(
            EC.presence_of_element_located((By.NAME, "password"))
        )
        password_element.send_keys(flight_retriever.password)
        password_element.submit()

        self._set_headers_from_request(driver)

        for request_made in driver.requests:
            if request_made.url == "https://mobile.southwest.com/api/security/v4/security/token":
                response = request_made.response
                
        if response.status_code != 200:
            error = self._handle_login_error(response)
            raise error

        # If this is the first time logging in, the account name needs to be set
        # because that info is needed later
        if flight_retriever.first_name is None:
            logger.debug("First time logging in. Setting account name")
            response_body = json.loads(response.body)
            self._set_account_name(flight_retriever, response_body)
            print(
                f"Successfully logged in to {flight_retriever.first_name} "
                f"{flight_retriever.last_name}'s account\n"
            )  # Don't log as it contains sensitive information

        # This page is also loaded when we log in, so we might as well grab it instead of
        # requesting again later
        for request_made in driver.requests:
            if request_made.url == "https://mobile.southwest.com/api/mobile-misc/v1/mobile-misc/page/upcoming-trips":
                flights = json.loads(request_made.response.body)["upcomingTripsPage"]
                print(flights)

        driver.quit()

        return [flight for flight in flights if flight["tripType"] == "FLIGHT"]
```

Rewriting the get_flights method to ensure the proper request is being parsed by checking the request url in webdriver.py fixes the issue.

**Comment by jdholtz** [comment]
Thanks for going into so much detail when reporting this (and even providing a fix)! 

It appears that your webdriver is capturing requests that we don’t want to capture. The `driver.scopes` variable (line 145 of lib/webdriver.py) is supposed to filter these out (more information on what that variable does [here](https://pypi.org/project/selenium-wire/#limiting-request-capture)). 

Does this issue still arise on the develop branch?

**Comment by fusionneo** [comment]
> Thanks for going into so much detail when reporting this (and even providing a fix)!
> 
> It appears that your webdriver is capturing requests that we don’t want to capture. The `driver.scopes` variable (line 145 of lib/webdriver.py) is supposed to filter these out (more information on what that variable does [here](https://pypi.org/project/selenium-wire/#limiting-request-capture)).
> 
> Does this issue still arise on the master branch?

Happy to help!

I can confirm the issue is still present on the master branch as well.

**Comment by jdholtz** [comment]
Can you add the following lines on line 111 of `lib/webdriver.py` (before `response = driver.requests[0].response`) and paste the output? 
```
for r in driver.requests:
    if r.response:
        print(r.url)
```
For me, the only two URLs that show up are 
```
https://mobile.southwest.com/api/security/v4/security/token
https://mobile.southwest.com/api/mobile-misc/v1/mobile-misc/page/upcoming-trips
```

**Comment by fusionneo** [comment]
```
https://accounts.google.com/ListAccounts?gpsia=1&source=ChromiumBrowser&json=standard
https://clientservices.googleapis.com/chrome-variations/seed?osname=win&channel=stable&milestone=112
https://clients2.google.com/service/update2/crx?os=win&arch=x86&os_arch=x86_64&nacl_arch=x86-64&prod=chromecrx&prodchannel=&prodversion=112.0.5615.121&lang=en-US&acceptformat=crx3&x=id%3Defaidnbmnnnibpcajpcglclefindmkaj%26v%3D0.0.0.0%26installedby%3Dexternal%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dghbmnnjooekpmoecnnnilnnbdlolhkhi%26v%3D0.0.0.0%26installedby%3Dinternal%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dgjgfobnenmnljakmhboildkafdkicala%26v%3D0.0.0.0%26installedby%3Dexternal%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dljglajjnnkapghbckkcmodicjhacbfhk%26v%3D0.0.0.0%26installedby%3Dexternal%26uc%26ping%3Dr%253D-1%2526e%253D1&x=id%3Dnmmhkkegccagdldgiimedpiccmgmieda%26v%3D0.0.0.0%26installedby%3Dother%26uc%26ping%3Dr%253D-1%2526e%253D1
https://mobile.southwest.com/api/security/v4/security/token
https://mobile.southwest.com/api/mobile-misc/v1/mobile-misc/page/upcoming-trips
```

These are the URLs being captured.

I can also confirm driver.scopes is set.

```
def _get_driver(self) -> Chrome:
        logger.debug("Starting webdriver for current session")
        chromedriver_path = self.checkin_scheduler.flight_retriever.config.chromedriver_path
        chrome_version = self.checkin_scheduler.flight_retriever.config.chrome_version
        driver = Chrome(
            driver_executable_path=chromedriver_path,
            options=self.options,
            seleniumwire_options=self.seleniumwire_options,
            version_main=chrome_version,
        )
        driver.scopes = [LOGIN_URL, TRIPS_URL, RESERVATION_URL]  # Filter out unneeded URLs

        logger.debug("Loading Southwest Check-In page")
        driver.get(CHECKIN_URL)
        return driver
```

**Comment by jdholtz** [comment]
I appreciate you taking your time to debug this and try my suggestions. It appears that the scopes are working. However, Chrome is possibly requesting to Google when it is initialized. Could you add `del driver.requests` before the driver.scopes? This will ensure all requests are removed before setting the URL scopes.

**Comment by fusionneo** [comment]
That fixed it! Thanks for your help with debugging this.
