### ISSUE TITLE
Failure Starting Webdriver

### ISSUE THREAD

**Issue by GitterDone221** [jdholtz/auto-southwest-check-in#82]
### Description

System: Fedora 36
Python: 3.10.8
PIP: 23.1.2
Auto-Southwest Check-In v3.1

I am running into following issue when trying to run script with simple reservation conf code.
Not sure what exactly is failing, but looks like webdriver initialization run into issues.

[john@fedora auto-southwest-check-in]$ python3 southwest.py -v [SW Conf Code] [First Name] [Last Name]

<details>
<summary>Output</summary>

2023-04-28 13:04:02 DEBUG MainProcess[log]: Initialized the application
2023-04-28 13:04:02 DEBUG MainProcess[main]: Called with 3 arguments
2023-04-28 13:04:02 DEBUG MainProcess[config]: Reading the configuration file
2023-04-28 13:04:02 DEBUG MainProcess[config]: No configuration file found. Using defaults
2023-04-28 13:04:02 DEBUG MainProcess[main]: Flight added through CLI arguments
2023-04-28 13:04:02 DEBUG MainProcess[main]: Monitoring 0 accounts and 1 flights
2023-04-28 13:04:02 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-04-28 13:04:02 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-04-28 13:04:02 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-04-28 13:04:02 DEBUG Process-1[webdriver]: Starting webdriver for current session
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib64/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/john/source/auto-southwest-check-in/lib/flight_retriever.py", line 37, in schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "/home/john/source/auto-southwest-check-in/lib/checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "/home/john/source/auto-southwest-check-in/lib/checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "/home/john/source/auto-southwest-check-in/lib/webdriver.py", line 60, in set_headers
    driver = self._get_driver()
  File "/home/john/source/auto-southwest-check-in/lib/webdriver.py", line 140, in _get_driver
    driver = Chrome(
  File "/home/john/.local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/john/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__
    browser = subprocess.Popen(
  File "/usr/lib64/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.10/subprocess.py", line 1722, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib64/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

</details>

Here is my pip freeze output
[john@fedora auto-southwest-check-in]$ pip freeze
<details>
<summary>Output</summary>

aiohttp==3.8.1
aiorpcX==0.22.1
aiosignal==1.2.0
apprise==1.3.0
argcomplete==2.0.0
asn1crypto==1.5.1
async==0.6.2
async-generator==1.10
async-mixin==0.0.3
async-timeout==4.0.2
asyncio-throttle==1.0.2
attr==0.3.2
attrs==21.4.0
base58==2.1.1
Beaker==1.10.0
beautifulsoup4==4.11.0
bidict==0.22.0
bitstring==3.1.9
blinker==1.6.2
blivet==3.4.4
blivet-gui==2.3.0
Brlapi==0.8.4
Brotli==1.0.9
build==0.8.0
CacheControl==0.12.11
cachy==0.3.0
certifi==2022.12.7
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.11
chicken==0.1.0
cleo==0.8.1
click==8.0.4
clikit==0.6.2
coincurve==17.0.0
colorama==0.4.5
coverage==7.2.4
crashtest==0.3.1
cryptography==40.0.2
cupshelpers==1.0
dasbus==1.6
DateTime==5.1
dbus-python==1.2.18
distlib==0.3.4
distro==1.6.0
dnspython==2.2.0
docopt==0.6.1
docopts==0.6.1
e-x==1.16.0
exceptiongroup==1.1.1
fail2ban==1.0.1
fedora-third-party==0.10
fido2==0.9.3
filelock==3.3.1
Flask==2.0.3
Flask-SocketIO==5.3.1
fros==1.1
frozenlist==1.3.0
gpg==1.17.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
html5lib==1.1
humanize==3.13.1
hyperframe==6.0.1
idna==3.3
iniconfig==2.0.0
itsdangerous==2.0.1
jeepney==0.8.0
Jinja2==3.0.3
kaitaistruct==0.10
keyring==23.7.0
langtable==0.0.60
libcomps==0.1.18
lockfile==0.12.2
lxml==4.7.1
Mako==1.1.4
Markdown==3.4.3
MarkupSafe==2.1.1
msgpack==1.0.4
multidict==6.0.2
nftables==0.1
oauthlib==3.2.2
olefile==0.46
onionshare==2.5
onionshare-cli==2.5
outcome==1.2.0
packaging==20.9
Paste==3.5.0
pastel==0.2.1
pep517==0.12.0
pexpect==4.8.0
pid==2.2.3
Pillow==9.1.0
pkginfo==1.8.3
platformdirs==2.3.0
pluggy==1.0.0
ply==3.11
plyvel==1.4.0
poetry==1.1.14
poetry-core==1.0.8
productmd==1.33
psutil==5.9.1
psycopg2-binary==2.9.3
ptyprocess==0.6.0
pwquality==1.4.4
pyasn1==0.5.0
pycairo==1.21.0
pycodestyle==2.10.0
pycparser==2.20
pycrypto==2.6.1
pycups==2.0.1
pycurl==7.45.1
pyenchant==3.2.2
PyGObject==3.42.1
pykickstart==3.36
pylev==1.4.0
pyln-bolt1==1.0.1.187.post0
pyln-bolt2==1.0.2.187.post0
pyln-bolt4==1.0.2.187.post0
pyln-bolt7==1.0.2.186.post0
pyln-client==0.11.1
pyln-proto==0.11.1
pylru==1.2.1
PyNaCl==1.5.0
pyOpenSSL==23.1.1
pyparsing==2.4.7
pyparted==3.12.0
PyQt5==5.12.2
PyQt5-sip==12.11.0
pyscard==1.9.7
PySide2==5.15.2.1
PySocks==1.7.1
pytest==7.3.1
pytest-cov==4.0.0
pytest-mock==3.10.0
python-augeas==1.1.0
python-dateutil==2.8.1
python-engineio==4.3.4
python-meh==0.50
python-socketio==5.7.1
pytz==2022.7.1
pyudev==0.22.0
pyxdg==0.27
PyYAML==6.0
qrcode==7.3.1
regex==2022.9.13
requests==2.28.2
requests-file==1.5.1
requests-ftp==0.3.1
requests-mock==1.10.0
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
rpm==4.17.1
SecretStorage==3.3.2
selenium==4.8.0
selenium-wire==5.1.0
selinux==3.3
sepolicy==3.3
setools==4.4.0
shellingham==1.4.0
shiboken2==5.15.2.1
simpleaudio==1.0.4
simpleline==1.9.0
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
sos==4.3
soupsieve==2.3.1
stem==1.8.0
systemd-python==234
Tempita==0.5.2
tomli==2.0.1
tomlkit==0.11.1
tqdm==4.64.0
trio==0.22.0
trio-websocket==0.10.2
undetected-chromedriver==3.1.7
Unidecode==1.3.6
urllib3==1.26.12
uuid==1.30
vcrpy==4.2.1
virtualenv==20.13.4
webencodings==0.5.1
websockets==10.3
Werkzeug==2.0.3
wrapt==1.15.0
wsproto==1.2.0
yarl==1.7.2
yubikey-manager==4.0.9
zope.interface==6.0
zstandard==0.21.0

 </details>

### To Reproduce

$python3 southwest.py -v [SW Conf Code] [First Name] [Last Name]

### Expected Behavior

expecting script to run without any errors

### Version

Auto-Southwest Check-In v3.1

**Comment by jdholtz** [comment]
Hi. Do you have Google Chrome (or a Chromium-based browser) installed? If not, that is the issue.

If so, this appears to be an issue with `undetected_chromedriver` (it looks like it can't find the chromedriver). Could you test undetected_chromedriver without using the script? 

Here's how to do it:
Enter the Python shell by executing `python3` in your terminial.

In the Python shell:
```
>>> import seleniumwire.undetected_chromedriver as uc
>>> uc.Chrome()
```

If that also reports the same error, you can set the [Chromedriver Path](https://github.com/jdholtz/auto-southwest-check-in/blob/master/CONFIGURATION.md#chromedriver-path) to the location of your Chromedriver for the script and see if that fixes the issue?

**Comment by jdholtz** [comment]
Hi @GitterDone221. Have you been able to try my suggestions above yet?

**Comment by jdholtz** [comment]
I will close this issue due to inactivity. I assume the issue is that a Chromium-based browser is not installed (or can’t be found), but I will reopen this issue once the suggestions above are tried
