### ISSUE TITLE
Getting error when adding confirmation code and name

### ISSUE THREAD

**Issue by wootwoot1234** [jdholtz/auto-southwest-check-in#84]
### Description

```
2023-05-01 09:37:38 DEBUG MainProcess[log]: Initialized the application
2023-05-01 09:37:38 DEBUG MainProcess[main]: Called with 3 arguments
2023-05-01 09:37:40 DEBUG MainProcess[config]: Reading the configuration file
2023-05-01 09:37:40 DEBUG MainProcess[config]: No configuration file found. Using defaults
2023-05-01 09:37:40 DEBUG MainProcess[main]: Flight added through CLI arguments
2023-05-01 09:37:40 DEBUG MainProcess[main]: Monitoring 0 accounts and 1 flights
2023-05-01 09:37:41 DEBUG Process-1[flight_retriever]: Scheduling reservations for 1 flights
2023-05-01 09:37:41 DEBUG Process-1[checkin_scheduler]: No headers set. Refreshing...
2023-05-01 09:37:41 DEBUG Process-1[checkin_scheduler]: Refreshing headers for current session
2023-05-01 09:37:41 DEBUG Process-1[webdriver]: Starting webdriver for current session
Process Process-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 976, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tom/Downloads/auto-southwest-check-in/lib/flight_retriever.py", line 37, in schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "/Users/tom/Downloads/auto-southwest-check-in/lib/checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "/Users/tom/Downloads/auto-southwest-check-in/lib/checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "/Users/tom/Downloads/auto-southwest-check-in/lib/webdriver.py", line 60, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/tom/Downloads/auto-southwest-check-in/lib/webdriver.py", line 140, in _get_driver
    driver = Chrome(
             ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 242, in __init__
    patcher.auto()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 127, in auto
    release = self.fetch_release_number()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/undetected_chromedriver/patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
```

### To Reproduce

`python3 southwest.py XXXXXX My Name -v`

**Comment by jdholtz** [comment]
This is the same issue that was in #72. Can you try my suggestion there and see if that works?

**Comment by wootwoot1234** [comment]
That worked, thanks!
