### ISSUE TITLE
Failed to Check-in

### ISSUE THREAD

**Issue by pltrant** [jdholtz/auto-southwest-check-in#93]
### Description

```
Failed to check in to flight <X> for <Soandso>. Reason: Bad Request 400.
Check in at this url: https://mobile.southwest.com/check-in

Exception ignored in: <function Chrome.__del__ at 0x000001B9FBDDCEA0>
Traceback (most recent call last):
  File "C:\Users\Soandso\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
    self.quit()
  File "C:\Users\Soandso\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 68, in quit
    super().quit()
  File "C:\Users\Soandso\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid
```

### To Reproduce

1) Start `southwest.py` and wait for auto check-in.

### Version

Auto-Southwest Check-In v4.0

**Comment by jdholtz** [comment]
Hi. Can you please provide the logs for the failed check-in? Also, does the script fail the check-in again if you restart it?

The OSError is a problem with `undetected_chromedriver`, but it shouldn’t affect the check-in process at all as it occurred after the check-in.

**Comment by pltrant** [comment]
Sure, here's the log from today:
```
2023-05-23 05:49:52 DEBUG Process-1:1[checkin_scheduler]: Refreshing headers for current session
2023-05-23 05:49:52 DEBUG Process-1:1[webdriver]: Starting webdriver for current session
2023-05-23 05:49:54 DEBUG Process-1:1[webdriver]: Loading Southwest Check-In page
2023-05-23 05:49:59 DEBUG Process-1:1[webdriver]: Filling out a check-in form to get valid headers
2023-05-23 05:50:00 DEBUG Process-1:1[webdriver]: Setting valid headers from previous request
2023-05-23 05:50:00 DEBUG Process-1:1[checkin_handler]: Sleeping until check-in: 594 seconds...
2023-05-23 05:59:55 DEBUG Process-1:1[checkin_handler]: Attempting to check in
2023-05-23 05:59:55 DEBUG Process-1:1[checkin_handler]: Making GET request to check in
2023-05-23 06:00:05 DEBUG Process-1:1[checkin_handler]: Making POST request to check in
2023-05-23 06:00:27 DEBUG Process-1:1[checkin_handler]: Failed to check in. Error: Bad Request 400. Exiting
2023-05-23 06:00:27 DEBUG Process-1:1[notification_handler]: Sending failed check-in notification...
```

I manually checked in for the flight after it failed.  When I restart the script, it does show this:
```
PS C:\Users\Soandso\OneDrive\Apps\Southwest_Check_in\auto-southwest-check-in> python .\southwest.py
Successfully logged in to Soandso1's account

Successfully scheduled the following flights to check in for Soandso1:
Flight from LocationA to LocationB at 2023-05-24 11:00:00 UTC
Flight from LocationB to LocationA at 2023-05-25 08:35:00 UTC

Checking in to flight from 'LocationA' to 'LocationB' for Soandso1

Successfully checked in to flight from 'LocationA' to 'LocationB' for Soandso1!
Soandso1 got B43!
Soandso2 got B44!
Soandso3 got B45!
Soandso1 got B10!
Soandso2 got B11!
Soandso3 got B12!
```

**Comment by jdholtz** [comment]
Hey @pltrant, did the script successfully check in for your return flight?

**Comment by pltrant** [comment]
Negative. Unfortunately, my PC had rebooted while I was away, so I had to manually check in. Go ahead and close out the issue. If it happens again, I'll create a new issue.
