### ISSUE TITLE
Chromedriver appears to be a higher version (114) than chrome can update to (113.0.5672.127)

### ISSUE THREAD

**Issue by davidamatthews** [jdholtz/auto-southwest-check-in#97]
### Description

Chromedriver appears to be a higher version (114) than chrome can update to (113.0.5672.127). Looks like it's [coming soon](https://developer.chrome.com/en/blog/new-in-chrome-114/), but is there a way to downgrade the chromedriver in the meantime so I can use the script? Or perhaps use a different browser/driver? Have had no issues in the past with this tool, seems to be a weird case!

### To Reproduce

Run python southwest.py CONFIRMATION FIRSTNAME LASTNAME

### Expected Behavior

Display flight information and waiting to check in message.

### Version

Auto-Southwest Check-In v4.0

### Additional context

<details>
<summary>Traceback</summary>

Process Process-1:
Traceback (most recent call last):
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "path\to\auto-southwest\auto-southwest-check-in\lib\flight_retriever.py", line 36, in monitor_flights
    self._schedule_reservations(flights)
  File "path\to\auto-southwest\auto-southwest-check-in\lib\flight_retriever.py", line 64, in _schedule_reservations
    self.checkin_scheduler.schedule(confirmation_numbers)
  File "path\to\auto-southwest\auto-southwest-check-in\lib\checkin_scheduler.py", line 36, in schedule
    self.refresh_headers()
  File "path\to\auto-southwest\auto-southwest-check-in\lib\checkin_scheduler.py", line 48, in refresh_headers
    webdriver.set_headers()
  File "path\to\auto-southwest\auto-southwest-check-in\lib\webdriver.py", line 59, in set_headers
    driver = self._get_driver()
             ^^^^^^^^^^^^^^^^^^
  File "path\to\auto-southwest\auto-southwest-check-in\lib\webdriver.py", line 142, in _get_driver
    driver = Chrome(
             ^^^^^^^
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 84, in __init__
    super().__init__(
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: **cannot connect to chrome at 127.0.0.1:58522
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 113.0.5672.127**
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0075A813+48355]
        (No symbol) [0x006EC4B1]
        (No symbol) [0x005F5358]
        (No symbol) [0x006161AC]
        (No symbol) [0x006106B4]
        (No symbol) [0x00610491]
        (No symbol) [0x00640C55]
        (No symbol) [0x0064093C]
        (No symbol) [0x0063A536]
        (No symbol) [0x006182DC]
        (No symbol) [0x006193DD]
        GetHandleVerifier [0x009BAABD+2539405]
        GetHandleVerifier [0x009FA78F+2800735]
        GetHandleVerifier [0x009F456C+2775612]
        GetHandleVerifier [0x007E51E0+616112]
        (No symbol) [0x006F5F8C]
        (No symbol) [0x006F2328]
        (No symbol) [0x006F240B]
        (No symbol) [0x006E4FF7]
        BaseThreadInitThunk [0x777C00C9+25]
        RtlGetAppContainerNamedObjectPath [0x77957B4E+286]
        RtlGetAppContainerNamedObjectPath [0x77957B1E+238]

Exception ignored in: <function Chrome.__del__ at 0x000001A28C2C3F60>
Traceback (most recent call last):
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
    self.quit()
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\webdriver.py", line 68, in quit
    super().quit()
  File "path\to\auto-southwest\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
    time.sleep(0.1)
OSError: [WinError 6] The handle is invalid
</details>

**Comment by jdholtz** [comment]
You can specify the chrome version in the configuration file. See [here](https://github.com/jdholtz/auto-southwest-check-in/blob/master/CONFIGURATION.md#chrome-version). Just set it to 113 and you should be good to go.

**Comment by davidamatthews** [comment]
Thanks so much! :)
