### ISSUE TITLE
You Cannot reuse the ChromeOptions object

### ISSUE THREAD

**Issue by babehboi** [jdholtz/auto-southwest-check-in#98]
### Description

It just started happening today, where I'm getting the webdriver: RuntimeError ('you cannot reuse the ChromeOptions object')

2023-05-31 15:28:27 DEBUG MainProcess[log]: Initialized the application
2023-05-31 15:28:27 DEBUG MainProcess[main]: Called with 2 arguments
2023-05-31 15:28:28 DEBUG MainProcess[config]: Reading the configuration file
2023-05-31 15:28:28 DEBUG MainProcess[config]: Adding 0 accounts from configuration file
2023-05-31 15:28:28 DEBUG MainProcess[config]: Setting check fares to True
2023-05-31 15:28:28 DEBUG MainProcess[config]: Adding 0 flights from configuration file
2023-05-31 15:28:28 DEBUG MainProcess[config]: Setting notification level to 1
2023-05-31 15:28:28 DEBUG MainProcess[config]: Using 1 notification services
2023-05-31 15:28:28 DEBUG MainProcess[config]: Setting retrieval interval to 24 hours
2023-05-31 15:28:28 DEBUG MainProcess[main]: Account added through CLI arguments
2023-05-31 15:28:28 DEBUG MainProcess[main]: Monitoring 1 accounts and 0 flights
2023-05-31 15:28:28 DEBUG Process-1[flight_retriever]: Retrieving flights for account
2023-05-31 15:28:28 DEBUG Process-1[webdriver]: Starting webdriver for current session
2023-05-31 15:28:29 DEBUG Process-1[webdriver]: An exception occured when initializing the webdriver: WebDriverException()
2023-05-31 15:28:29 DEBUG Process-1[webdriver]: 2 more attempts
2023-05-31 15:28:29 DEBUG Process-1[webdriver]: An exception occured when initializing the webdriver: RuntimeError('you cannot reuse the ChromeOptions object')
2023-05-31 15:28:29 DEBUG Process-1[webdriver]: 1 more attempts
2023-05-31 15:28:30 DEBUG Process-1[webdriver]: An exception occured when initializing the webdriver: RuntimeError('you cannot reuse the ChromeOptions object')
2023-05-31 15:28:30 DEBUG Process-1[webdriver]: 0 more attempts
Process Process-1:
Traceback (most recent call last):
  File "/home/user/auto-southwest-check-in/lib/webdriver.py", line 165, in _init_driver
    driver = Chrome(
  File "/usr/local/lib/python3.10/dist-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/undetected_chromedriver/__init__.py", line 252, in __init__
    raise RuntimeError("you cannot reuse the ChromeOptions object")
RuntimeError: you cannot reuse the ChromeOptions object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/auto-southwest-check-in/lib/flight_retriever.py", line 119, in monitor_account
    flights = self._get_flights()
  File "/home/user/auto-southwest-check-in/lib/flight_retriever.py", line 135, in _get_flights
    flights = webdriver.get_flights(self)
  File "/home/user/auto-southwest-check-in/lib/webdriver.py", line 90, in get_flights
    driver = self._get_driver()
  File "/home/user/auto-southwest-check-in/lib/webdriver.py", line 140, in _get_driver
    driver = self._init_driver()
  File "/home/user/auto-southwest-check-in/lib/webdriver.py", line 178, in _init_driver
    raise RuntimeError(
RuntimeError: Failed to initialize the webdriver after 3 attempts
user@user-ubuntu:~/auto-southwest-check-in$

### To Reproduce

1. Run script with any flight with more than 1 leg (aka RT)
- it can be logging in username password
- or via confirmation number name last name
2. Error will ensue.

### Expected Behavior

It just checks the flights accordingly.

### Version

4.0

### Additional context

I have attempted to update everything. Running I believe Chrome 114 now as well.

Running a request with 1 leg where using 'confirmation firstname lastname' works appropriately.

**Comment by jdholtz** [comment]
Thanks for reporting this @babehboi. This was an issue that popped up from my last improvement to the webdriver initialization. I fixed it and modified a test to ensure it doesn't happen again.
